Refactoring `matrix_inv` function
phoenix-pilot/phoenix-pilot-core pull request #111
Opened 2022-09-12 16:13 UTC by PNieck

## Description

This PR changes implementation of function `matrix_inv`. Now function:
- return $-1$ when matrix to inverse is not a square
- return $-1$ when buffer is too short
- return $-1$ when it is impossible to invert matrix (determinant is equal to $0$)

## Motivation and Context

Better interface for `matrix` library

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [x] New test added: (add PR link here). In this PR
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-09-23 08:51 UTC, niewim19 requested changes

2022-09-23 08:51 UTC, niewim19 commented on algebra/tests/matrix/inverse.c
> +/* Our algorithm have problems with zeroes on main diagonal */
Your _ignore-informing_ message is good :) Just refactor it in such way it matches our typical TEST_IGNORE message please.

Here is reference in two tests:
https://github.com/phoenix-rtos/phoenix-rtos-tests/blob/0c911be5bca81ad877759736fd413f94fd697df2/libc/unistd_uids.c#L47-L77

2022-09-23 08:51 UTC, niewim19 commented on algebra/tests/matrix/inverse.c
> +}
No newline at the end

2022-09-23 10:27 UTC, PNieck commented on algebra/tests/matrix/inverse.c
> +	/* Exp = A^(-1) */
Yes, my mistake

2022-09-26 11:20 UTC, niewim19 requested changes

2022-09-26 11:20 UTC, niewim19 commented on algebra/tests/matrix/inverse.c
> +	/* M1 = J */
```suggestion
	/* M1 = J, J is invertable. Tests will modify it in different way so that it is incorrect */
```

2022-09-26 11:20 UTC, niewim19 commented on algebra/tests/matrix/inverse.c
> +	}
To omit magic numbers, we can copy first row to the last row. That way no magic numbers are used.

2022-09-26 14:37 UTC, niewim19 approved these changes
LGTM

2022-09-26 14:37 UTC, merged