Fixing `vec_normal` function
phoenix-pilot/phoenix-pilot-core pull request #118
Opened 2022-09-14 14:19 UTC by PNieck

## Description

In this PR behavior of function `vec_normal` was changed. Now function returns perpendicular vector, when paraller vectors are passed to it. Moreover there are tests for this function.

## Motivation and Context

Better interface for vectors library.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [x] New test added: (add PR link here).In this PR
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-09-14 19:38 UTC, niewim19 requested changes

2022-09-14 19:38 UTC, niewim19 commented on algebra/vec.c
> +				vec_times(C, 0);
You were right with multiplication being useless. Lets just hand-type there zeroes.

2022-09-14 19:38 UTC, niewim19 commented on algebra/tests/vec/various.c
> +#define DELTA 5e-6
Add comment regarding this macro, please.

2022-09-14 19:38 UTC, niewim19 commented on algebra/tests/vec/various.c
> +	TEST_ASSERT_FLOAT_WITHIN(DELTA, 0.0, vec_dot(&A, &C));
How about new macro `TEST_ASSERT_PERPENDICULAR_VEC()`?

2022-09-14 19:38 UTC, niewim19 commented on algebra/tests/vec/various.c
> +	vec_t A = V1;
as discussed - please use small letters in new PR-s

2022-09-14 19:38 UTC, niewim19 commented on algebra/tests/vec/various.c
> +TEST(group_vec_normal, vec_normal_oneZeroVector)
Please add mathematical themed comment regarding this edge case

2022-09-14 19:38 UTC, niewim19 commented on algebra/tests/vec/various.c
> +TEST(group_vec_normal, vec_normal_bothZeroVectors)
Please add mathematical themed comment regarding this corner case

2022-09-15 08:50 UTC, PNieck commented on algebra/tests/vec/various.c
> +	TEST_ASSERT_FLOAT_WITHIN(DELTA, 0.0, vec_dot(&A, &C));
Yes, I also thought about it

2022-09-15 15:46 UTC, niewim19 requested changes

2022-09-15 15:46 UTC, niewim19 commented on algebra/vec.c
> +	if (lenSquared == 0) {
How about dropping the far nesting of `if`s and use multiple returns? Something like:
 - do a cross
 - if `len != 0` return
 - do different cross
 - if `len != 0` return
 - do different cross
 - final if and returns

2022-09-16 12:09 UTC, PNieck commented on algebra/vec.c
> +	const vec_t *longerV;
I cannot do that, because I am changing `v` in this function

2022-09-20 06:33 UTC, niewim19 requested changes

2022-09-20 06:33 UTC, niewim19 commented on algebra/vec.c
> +	longerV = (vec_dot(A, A) > vec_dot(B, B)) ? A : B;
Please, add comments after each, non-final return regarding what is the next scenario

2022-09-20 06:33 UTC, niewim19 commented on algebra/tests/vec/various.c
> +	TEST_ASSERT_UNIT_VEC(c);
Isn't it supposed to have different arguments order? I can`t find the difference between this part, and above

2022-09-20 09:03 UTC, niewim19 submitted a review, later dismissed
LGTM

2022-09-20 10:19 UTC, merged