Tests for `quat_sandwich`
phoenix-pilot/phoenix-pilot-core pull request #119
Opened 2022-09-14 16:54 UTC by PNieck

## Description

This PR contains test for `quat_sandwich` function. Moreover it fixes this function.

## Motivation and Context

More precise tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-09-14 18:37 UTC, niewim19 requested changes
Very good catch in quad_sandwitch implementation!

Only small remarks.

2022-09-14 18:37 UTC, niewim19 commented on algebra/tests/quat/various.c
> +/* 613861170.772044 - 27264873.204711974i + 1092723638.076936j - 1585712993.277524k */
This comment doubles the information from the quat below. Is it necessary?

2022-09-14 18:37 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	quat_t C;
As discussed please use lowercase for local variables in testbody (with exception to matrices)

2022-09-15 08:34 UTC, PNieck commented on algebra/tests/quat/various.c
> +/* 613861170.772044 - 27264873.204711974i + 1092723638.076936j - 1585712993.277524k */
Sorry, my mistake - I have forgotten to delete it

2022-09-15 16:04 UTC, niewim19 approved these changes
LGTM

2022-09-16 11:02 UTC, merged