Fixing and adding tests for `quat_uvec2uvec` function
phoenix-pilot/phoenix-pilot-core pull request #131
Opened 2022-09-19 11:44 UTC by PNieck

## Description

In this PR I have fixed `quat_uvec2uvec` function. Now function check if passed vectors are parallel or antiparallel in a proper way. Moreover I have added tests for this function.

## Motivation and Context

More robust functions.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [x] New test added: (add PR link here). In this PR
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-09-20 09:20 UTC, niewim19 requested changes

2022-09-20 09:20 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	vec_normalize(&v2);
```suggestion
	quat_t q;
	vec_t v1 = V1;
	vec_t v2 = V1rotQ8;

	vec_normalize(&v1);
	vec_normalize(&v2);
```
This is more readable, plus a split between declarations and function body is necessary. Applies in more tests.

2022-09-20 09:20 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	;
To be removed

2022-09-20 09:20 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	v2.y += 0.1;
Is it sufficiently small change to cover near-parallelity case?

2022-09-20 09:20 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	vec_times(&v2, -1);
Add small comment here, something like `Making v1 and v2 unitary and antiparallel`

2022-09-20 10:34 UTC, PNieck commented on algebra/tests/quat/various.c
> +	v2.y += 0.1;
Yes, it is. I have checked this. In this test `vec_dot(&v1, &v2)` is equal to $0.997208$, so it is small enough.

2022-09-21 12:53 UTC, niewim19 requested changes

2022-09-21 12:53 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	TEST_ASSERT_EQUAL_VEC(v2, v1);
Please add comment why we are not checking `q` against `Q8` as it might seem reasonable but is wrong in this case, and each other testcase

2022-09-21 12:53 UTC, niewim19 commented on algebra/tests/quat/various.c
> +	v2 = v1;
Remark not addressed :)

2022-09-21 14:17 UTC, merged