pilot-core: accelerometer calibration implementation
phoenix-pilot/phoenix-pilot-core pull request #160
Opened 2022-10-11 14:18 UTC by niewim19

## Description

This PR implements following things:
 1) accelerometer rotation (`accrot`) calibration as a calibration type in `libcalib`
 2) `accrot` calibration procedure in `calibtool` that can calculate calibration parameters
 3) `accrot` parameters usage in `libsensc`
 4) strict usage of NED frame of reference in calcuations across `ekf` and all calibration procedures 

And additionally:
 - implements `quat_len()` function to algebra library

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-10-11 14:20 UTC, niewim19 commented on libs/calib/calib.h
> +typedef enum { typeMagmot = 0, typeMagiron, typeMotlin, typeAccrot } calibType_t;
unresolvable

2022-10-11 14:23 UTC, niewim19 commented
# Ready for review

As it comes out the codespell ignore feature is not yet accessible on this repository, so it still gets angry over `NED` and `qEst` words in code

2022-10-11 15:09 UTC, HBuczynski requested changes

2022-10-11 15:09 UTC, HBuczynski commented on calib/accrot.c
> +	const quat_t idenQ = { .a = 1, .i = 0, .j = 0, .k = 0 };
`static const`

2022-10-11 15:09 UTC, HBuczynski commented on ekf/kalman_update_imu.c
> +	vec_t magxacc, gDiff;
`magxacc` - I don't understand this variable

2022-10-11 15:09 UTC, HBuczynski commented on .codespell_ignore
> +qEst
new line

2022-10-11 16:21 UTC, niewim19 commented on calib/accrot.c
> +#include "calibtool.h"
Yeah, that's too many. Reviewed them and left only necessary ones.

2022-10-11 16:21 UTC, niewim19 commented on calib/accrot.c
> +#define VECTOR_
No, that's a leftover. Thanks for pointing it out!

2022-10-11 16:21 UTC, niewim19 commented on libs/calib/calib.c
> +	/* variable casting for MISRA compliance */
This was done like in other casting methods, so comment was also copied here. I have removed all three of such comments in _libs/calib/calib.c_

2022-10-11 16:21 UTC, niewim19 commented on libs/calib/calib.c
> +			break;
Thanks, added!

PS. This `default` statement is probably impossible to trigger, because there is strict value check just before `switch`.

2022-10-11 16:21 UTC, niewim19 commented on calib/accrot.c
> +	}
I moved addition of `sensc_init` further  down the branch to commit with `accrot` implementation in calibtool

2022-10-12 08:27 UTC, HBuczynski approved these changes

2022-10-12 08:37 UTC, merged