Flight schedule parser
phoenix-pilot/phoenix-pilot-core pull request #165
Opened 2022-10-17 09:08 UTC by PNieck

This PR contains parser for flight schedule.

## Description

We don't have to recompile the whole program to change drone behavior.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [x] New test added: (add PR link here). In this PR
- [x] Tested by hand on: (list targets here). `host-generic-pilot`, `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-10-18 10:21 UTC, HBuczynski requested changes
Remarks for the library logic. Only the first commit was reviewed.

2022-10-18 10:21 UTC, HBuczynski commented on libs/parser/parser.c
> +	}
Adding additional `hmap` is not the best approach. The code becomes more complicated and there is many dynamic allocations.

The easiest way:
`
typedef struct {
	const char *field;
	const char *val;
} parser_result_t;
`

The converter:
`
void (*converter)(parser_result_t *, size_t len)
`
The goal of the library is to parse header and fields and provide `parser_result_t ` array for the calling unit.
Code is less complicated and you don't have to bother which unit should alloc and free `result` data.

2022-10-18 10:21 UTC, HBuczynski commented on libs/parser/parser.c
> +	}
I don't think that there is a need to perform `fileCheck` before parsing. In this case, you have to iterate the whole file twice. During parsing, you can check whether the file is syntactically correct.

2022-10-20 15:22 UTC, PNieck commented on libs/parser/parser.c
> +	}
I have done it in a different way. Program is compiling and freeing regexes according to number of `parser` instances.
First allocation => compile regexes
Last deallocation => free regexes

2022-10-20 15:24 UTC, PNieck commented on libs/parser/parser.c
> +int parser_parse(parser_t *p, const char *path, parser_result_t **result, int *resultLen)
Ok, I have rewritten this function

2022-10-20 15:26 UTC, PNieck commented on libs/parser/parser.c
> +	}
Ok, I have changed approach - `hmap` have stood as it is, but now there is not so many allocation.

2022-10-21 09:36 UTC, HBuczynski requested changes

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +	return result;
Add new line;

```suggestion
	parser_common.refs++;
	
	return result;
```

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +	return -1;
In our code style, we try to limit the amount of returns in the code.

```suggestion
        int err = -1;
	if (regexec(&(parser_common.headerRegex), line, HEADER_SUBEXPRESSIONS, regmatch, 0) == 0) {
		headerLen = regmatch[1].rm_eo - regmatch[1].rm_so;
		if (headerLen < MAX_HEADER_LEN) {
		        strncpy(result, &line[regmatch[1].rm_so], headerLen);
		        result[headerLen] = '\0';
		        err = 0;
		}
	}

	return err;
```

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +		}
```suggestion
	while (getline(&line, &lineLen, file) != -1) {

```

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +	int result, i, error = 0;
```suggestion
	int res, i, err = 0;
```

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +						error = 1;
Keep the convention.
Parser usually returns `-1` if the error occurs.

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +				if (headerInfo != NULL && p->fieldsMap->size > 0) {
Do you need to check `fieldsMap->size`?

2022-10-21 09:36 UTC, HBuczynski commented on libs/parser/parser.c
> +				if (hmap_insert(p->fieldsMap, (p->fields + i)->field, (p->fields + i)->value) != 0) {
```suggestion
				if (hmap_insert(p->fieldsMap, p->fields[i]->field, p->fields[i]->value) != 0) {
```

2022-10-21 10:07 UTC, PNieck commented on libs/parser/parser.c
> +				if (headerInfo != NULL && p->fieldsMap->size > 0) {
You are right, we don't have to

2022-10-24 07:45 UTC, HBuczynski requested changes
General parser library LGTM. Some minor comments to documentation and tests:
**Doc:**
1. I would not create a separate file for each function, gather them to one file `api.md` and put in the same directory as README.md.
2. There are some language and grammar mistakes.. Please check it using `grammarly` or other external tool.

Tests:
1. Please keep one files naming convention compliant with the rest of the library: `emptyFile` -> `empty_file`.

2022-10-24 07:45 UTC, HBuczynski commented on libs/parser/tests/files/spaces
> +INT2=16
up

2022-10-24 07:45 UTC, HBuczynski commented on libs/parser/doc/README.md
> +#include <parser.h>
`hmap.h` is already in `parser.h`
```suggestion
#include <parser.h>
```

2022-10-24 11:38 UTC, niewim19 requested changes
General remark: please equip significant error returns with some error message (through `perror()` or `fprintf(stderr, ...)). Making simple mistake in config file is extremely easy, but finding it without any knowledge of what went wrong is hard.

Parser looks good, some improvements were suggested in remarks. Thread safety should be ensured across parser library as currently conflicts may arise in an unfortunate timing scenario.

2022-10-24 11:38 UTC, niewim19 commented on libs/parser/parser.c
> +enum parser_lineType { lineType_Header, lineType_Field, lineType_Comment, lineType_InvalidLine };
Meeting enum naming convention (+shorter):
```suggestion
enum parser_lineType { type_header, type_field, type_comment, type_invalid };
```

2022-10-24 11:38 UTC, niewim19 commented on libs/parser/parser.c
> +	strcpy(p->headerInfos[id].headerName, headerName);
There is probably no need to store header name in separate place, as it should be passed as a string literal, so just storing the pointer to const char* is enough (it will be accessible throughout whole program execution)

2022-10-24 11:38 UTC, niewim19 commented on libs/parser/parser.c
> +}
I would suggest to implement this function directly into loop where it is currently used. The goal is to acquire header info from hashmap of headers, and we can directly work on `line[regmatch[1].rm_so]` with `hmap_get()`. The same applies to `parser_fieldGet`. There is no need to make copy of these strings if we are not loosing the original.

2022-10-24 11:38 UTC, niewim19 commented on libs/parser/parser.c
> +}
This wrapper is quite short and has the same amount of if-checking as direct usage of `headerInfo->converter(fieldsMap) != 0` in loop :) Direct implementation in loop may be applied here.

Also: we can use `converter` return value directly as an error value.

2022-10-27 09:35 UTC, PNieck commented on libs/parser/parser.c
> +}
I cannot do that. Header line can contain characters after the end of header name - for example comment or white spaces. `hmap_get` takes only `char *` as an argument, so it is  reading whole line.

Moreover I have to copy field name and value. In there case I would have only a pointer to the character in `line` string. This variable is changing with every invocation of `getline` function

2022-10-27 17:40 UTC, HBuczynski requested changes

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/parser.c
> +	}
```suggestion
	if (feof(file) == 0) {
		fprintf(stderr, "Parser: error occurred during file parsing\n");
		err = -1;
	}
	else	if (headerInfo != NULL && p->fieldsMap->size != 0) {
		err = headerInfo->converter(p->fieldsMap)
		if (err != 0) {
			fprintf(stderr, "Parser: there was an error during converter invocation\n");
		}
	}
	
	
	.
	.
	.
	return err;
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/README.md
> +# Documentation of `parser.h` library
```suggestion
# Parser library
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/README.md
> +- Library overview
```suggestion
- API
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +This is main the parser structure. It contains all the necessary data needed for parsing.
```suggestion
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +- [Table of contents](README.md)
Remove it from the whole file

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +- `maxFieldsNb` - maximum number of fields connected to one header
```suggestion
- `maxFieldsNb` - maximum number of fields described by the header
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +- `maxHeadersNb` - maximum number of headers that can be specified in a parser
```suggestion
- `maxHeadersNb` - maximum number of headers that can be declared in a parser
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +**Returns:**
```suggestion
**Return value:**
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +- In case of a successful completion function returns a pointer to the correctly allocated `parser_t` structure.
```suggestion
- On success, a pointer to the correctly allocated `parser_t` structure is returned.
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +- In case of an error function returns `NULL`
Please update other functions in similar convention as well. Take a look how it is done in the other projects: https://man7.org/linux/man-pages/man2/read.2.html

```suggestion
- On error, `NULL` is returned.
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +
```suggestion
Function frees structure `p` allocated by the `parser_alloc` function. If `p` is equal to `NULL`, function does nothing.

```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +Function defines new header in parser `p`. After this function parser is able to recognize and parse a file, which contains such a header. It is possible to specify no more header than was specified
```suggestion
Function defines a new header in parser `p`. Library can only parse headers declared via this function. Header names are unique within `p`.
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +# Converter function
```suggestion
# Converter Handler
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +The function has to get as an argument hash map `hmap` and return an integer.
There is a function prototype so this description is not needed.
```suggestion

```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +    char *intValue, floatValue;
```suggestion
    char *intValue, *floatValue; 
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +	return 0;
indentation

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/api.md
> +
TO be fixed

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/file.md
> +# Appropriate file for parser
```suggestion
# Files syntax
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/file.md
> +Parser from this library can parser only files that are consistent with this documentation. If an incorrect file is used function `parser_parse` returns an error.
```suggestion
Parser recognizes only syntax described below. Non-compliance with the convention causes errors during the parsing process.
```

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/doc/file.md
> +- [white lines](#white-line)
These links are useless. You describe these categories below.

2022-10-27 17:40 UTC, HBuczynski commented on libs/parser/tests/files/spaces
> +INT2=16
You have not fixed it.

2022-10-28 12:23 UTC, PNieck commented on libs/parser/parser.c
> +	strcpy(p->headerInfos[id].headerName, headerName);
Ok, but there is a problem. What about situation, when someone invokes `parser_headerAdd` with local strings in other function that `parser_parse`

2022-10-28 12:47 UTC, PNieck commented on libs/parser/tests/files/spaces
> +INT2=16
I have thought that you meant to add new line between fields. This is part of a test that there is no newline. In first version of parser there were bugs in such a situation.

2022-10-28 15:06 UTC, HBuczynski commented on libs/parser/doc/README.md
> +    - [Converter function](api.md#converter-handler)
```suggestion
    - [Converter handler](api.md#converter-handler)
```

2022-10-28 15:06 UTC, HBuczynski commented on libs/parser/doc/README.md
> +    - [`parser_headerAdd` function](api.md#parser_headeradd-function)))
brackets

2022-10-28 15:41 UTC, HBuczynski requested changes
Please update `various.c` file to be consistent with convention in `parsing.c`

2022-10-28 15:41 UTC, HBuczynski commented on libs/parser/tests/parsing.c
> +	}
add new line

2022-10-28 15:41 UTC, HBuczynski commented on libs/parser/tests/parsing.c
> +			break;
```suggestion
		case 1:
			res += test_hmapSizeCheck(h, 3);
			res += test_fieldCheck(h, INT1_FIELD_NAME, "5");
			res += test_fieldCheck(h, FLOAT_FIELD_NAME, "2.5");
			res += test_fieldCheck(h, STRING_FIELD_NAME, "TEST");
			break;
			
```

2022-10-28 15:41 UTC, HBuczynski commented on libs/parser/tests/main.c
> +	return 0;
```suggestion
	UnityMain(argc, (const char **)argv, runner);
	
	return 0;
```

2022-10-31 10:54 UTC, niewim19 requested changes
NIce to see very verbose parser. It will be easy to debug wrong parser configuration or file structure! 

I think that as there are many errors of similar type/error message in multiple parser functions you can pass the function name as first argument in each error message. Something like this:

```c
#define FUNCNAM_HEADERADD "parser_headerAdd"
#define FUNCNAM_EXECUTE       "parser_execute"

int parser_headerAdd(...)
{
    fprintf(stderr, "%s: error message!", FUNCNAM_HEADERADD);
}

int parser_execute(...)
{
    fprintf(stderr, "%s: error message!", FUNCNAM_EXECUTE);
}
```

This idea meets well with multiple cases of e.g `invalid arguments` error message which now needs to be changed only for the reason of being easy to distinguish between functions.

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +		fprintf(stderr, "Parser: an error occurred during Regex compilation.\n");
Please use imperative/nominal sentences as error messages (if possible). They are always shorter and straight informative.
```suggestion
		fprintf(stderr, "Parser: error on Regex compilation.\n");
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +		fprintf(stderr, "Parser: invalid arguments. Both of them have to be bigger than zero.\n");
Unclear error message. User may be confused about _both of  what_ has to be bigger than zero. You can use variable names directly like:
```suggestion
		fprintf(stderr, "Parser: invalid maxHeadersNb/maxFieldsNb arguments\n");
```
Or change those arguments to unsigned int and then have only:
```suggestion
		fprintf(stderr, "Parser: invalid arguments. Header or fields number equal to zero.\n");
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +		fprintf(stderr, "Parser: error during hash map initialisation\n");
Error message ambiguity with line 137. You can use:
```suggestion
		fprintf(stderr, "Parser: headers map initialization error\n");
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +		fprintf(stderr, "Parser: error during hash map initialisation\n");
Error message ambiguity with line 120. You can use:
```suggestion
		fprintf(stderr, "Parser: fields map initialization error\n");
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +	strcpy(p->headerInfos[id].headerName, headerName);
No need for that. Just write in documentation that string literals must be used and not local variables :)

Case you pointed out means that someone dynamically configures the parser. So there would be a configuration of parser configuration :) If we ever achieve that level of sophistication we will just write json parser. However its good you pointed this out.

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +		fprintf(stderr, "Parser: it is impossible to define two headers with the same names\n");
Please use imperative/nominal sentences as error messages (if possible). They are always shorter and straight informative.
```suggestion
		fprintf(stderr, "Parser: header %s already exists!\n", p->headerInfos[id].headerName);
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +						fprintf(stderr, "Parser: there was an error during converter invocation\n");
Please use imperative/nominal sentences as error messages (if possible). They are always shorter and straight informative.
```suggestion
						fprintf(stderr, "Parser: error on converter invocation\n");
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +					fprintf(stderr, "Parser: where was an error during parsing header \"%s\"\n", line);
```suggestion
					fprintf(stderr, "Parser: error on parsing header \"%s\"\n", line);
```

2022-10-31 10:54 UTC, niewim19 commented on libs/parser/parser.c
> +	}
I would go for no early return and a message that regex compilation failed to give some idea why, probably, there is be an exception later in execution with no clear reason if this fail :)

2022-10-31 11:34 UTC, HBuczynski requested changes

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/doc/api.md
> +```
Missing at the end:
`## See also:
- [Table of contents](README.md)`

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/parser.c
> +	if (regcomp(&(parser_common.fieldRegex), FIELD_PATTERN, REG_EXTENDED) != 0) {
Add new line, there are separated conditions.

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/parser.c
> +	if (regcomp(&(parser_common.headerRegex), HEADER_PATTERN, REG_EXTENDED) != 0) {
Add new line, there are separated conditions.

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/parser.c
> +		regfree(&(parser_common.commentRegex));
```suggestion
		regfree(&parser_common.commentRegex);
```

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/parser.c
> +	if (regcomp(&(parser_common.commentRegex), COMMENT_PATTERN, REG_EXTENDED) != 0) {
Please, apply to the rest of the code
```suggestion
	if (regcomp(&parser_common.commentRegex, COMMENT_PATTERN, REG_EXTENDED) != 0) {
```

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/tests/parsing.c
> + * Unit tests for various functions from parser library
Upps, copy-paste.

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/tests/parsing.c
> +	data = hmap_get(h, fieldName);
```suggestion
	const char *data = hmap_get(h, fieldName);
```

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/tests/parsing.c
> +#define CHECK_OK 0
I would not use a specific define. You can explicitly compare the result from function to `0`.

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/tests/various.c
> +#define CHECK_OK 0
The same as in the previous test file.

2022-10-31 11:34 UTC, HBuczynski commented on libs/parser/tests/various.c
> +#define bufLen   15
Cammel case

2022-10-31 11:49 UTC, niewim19 reviewed
When it comes to documentation please adapt to out documentation formatting style:

https://github.com/phoenix-rtos/phoenix-rtos-doc/blob/1900ced925076996035c9b27ad67cdc489dd8a69/libc/functions/c/condCreate.phrtos.md

It will improve future use of this documentation in overall docs

2022-10-31 11:49 UTC, niewim19 commented on libs/parser/tests/parsing.c
> +/* Checks if hash map have key equal to `fieldName` and it's value is the same as`expValue. If succeeded returns 0. In other case returns -1. */
nit :)
```suggestion
/* Checks if hash map have key equal to `fieldName` and it's value is the same as `expValue`. If succeeded returns 0. In other case returns -1. */
```

2022-10-31 14:09 UTC, HBuczynski approved these changes

2022-10-31 14:55 UTC, merged