pilot-core: changes for flying practice
phoenix-pilot/phoenix-pilot-core pull request #168
Opened 2022-10-20 14:34 UTC by niewim19

## Description

Following changes were made to achieve working quadrocopter in real scenario flight

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-10-25 07:03 UTC, niewim19 commented on quadcontrol/control.c
> +			&& msg->channels[RC_LEFT_VSTICK_CH] <= minTriggerVal && quad_common.currFlight == flight_idle) {
I wouldn`t implement this suggestion as it makes code unreadable

2022-10-25 07:05 UTC, niewim19 commented on scripts/quadLive.py
> +        ser = serial.Serial(args.port, baudrate=args.baud, timeout=1)
it should be like that

2022-10-26 12:46 UTC, HBuczynski commented on quadcontrol/control.c
>  	now = quad_timeMsGet();
You can remove it.

2022-10-26 15:43 UTC, niewim19 commented on quadcontrol/control.c
> +	}
To emphasize mutex-locked part of code. Removed as requested.

Btw. our phoenix-rtos-doc coding convention does not restrict or even mention additional code block usage, or did I miss something?

2022-10-26 15:43 UTC, niewim19 commented on quadcontrol/control.c
>  }
If clause removal was recerted. Now it is copied only in `mode_rc`.

2022-10-26 15:44 UTC, niewim19 commented on quadcontrol/control.c
>  	now = quad_timeMsGet();
But then we risk uninitialized `throttle` variable if I switch SWD high during engines arming (by accident lets say). With this line we ensure that we start with throttle variable equal to that of RC transmitter. Also removing this line causes compilation warning of possible uninitialized variable.

2022-10-27 09:46 UTC, HBuczynski commented on quadcontrol/control.c
>  	now = quad_timeMsGet();
Ups, my mistake. The comment was to line 337.

2022-10-27 10:04 UTC, HBuczynski requested changes

2022-10-27 13:34 UTC, HBuczynski commented on quadcontrol/control.c
> +	const static uint16_t lowTrigTresh = 5 * (MAX_CHANNEL_VALUE - MIN_CHANNEL_VALUE) / 100 + MIN_CHANNEL_VALUE;
These lines are copied from `quad_rcbusHandler`. You can create defines and update also the `quad_rcbusHandler`

2022-10-28 07:03 UTC, niewim19 commented
All review remarks were implemented in old commits.

After last review two commits were added:
 - mma motors order change so that drone software front is in the same direction as drone hardware front
 - ekf development config read was added, as it was added each time manually for testing purposes

2022-10-28 07:34 UTC, HBuczynski commented on libs/mctl/mctl.c
> +*/
The comments inside a function are enough.

2022-10-28 07:34 UTC, HBuczynski commented on quadcontrol/control.c
> +#define RC_IIR_LATENCY  3
It is used only in one function. I would not make it a global define.
You can define it as `static const` inside `quad_iir`.

2022-10-28 07:34 UTC, HBuczynski commented on quadcontrol/control.c
> +	att.roll = 0;
```suggestion
	quad_att_t att = { 0 };
	time_t now, end;
	ekf_state_t measure;

	ekf_stateGet(&measure);

	att.yaw = measure.yaw;
```

2022-10-28 07:34 UTC, HBuczynski commented on quadcontrol/control.c
> +	att.roll = 0;
```suggestion
        quad_att_t att = { 0 };
	time_t spoolStart, spoolEnd, now;
	ekf_state_t measure;

	ekf_stateGet(&measure);

	att.yaw = measure.yaw;
```

2022-10-28 07:34 UTC, HBuczynski commented on quadcontrol/control.c
> +static int32_t quad_iir(int32_t curr, int32_t new)
```suggestion
static inline int32_t quad_iir(int32_t curr, int32_t new)
```

2022-10-28 07:34 UTC, HBuczynski commented on quadcontrol/control.c
> +	att.roll = 0;
The same case as above.

2022-10-28 07:48 UTC, HBuczynski approved these changes

2022-10-28 09:05 UTC, merged