utils: expand altlog to all sensors + utils creation
phoenix-pilot/phoenix-pilot-core pull request #169
Opened 2022-10-28 07:15 UTC by niewim19

- all ekf so-called test applications moved to `utils/` directory
 - namechange `altlog` -> `senslog`
 - `senslog` allows for selective sensor data logging in real time and to a file

JIRA: PP-95

## Description

 - ekf development applcications (stored in ekf/tests/ directory) are moved to separate utils directory
 - `altlog` utility heavily modified to `senslog` utility which provides selections of;
   - total sampling time
   - sampling interval
   - devices to sample from
   - corrections enable/disable

## Motivation and Context

For development purposes it is nice to have ability for flexible sensor logging. Currently it involved directly changing code of `devekf` or `sensortest` and it produced unreliable logs (each implementation was different).

It will be decided if similar application will be developed for EKF or EKF will be embeded into this app in the future.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-10-31 15:30 UTC, HBuczynski requested changes

2022-10-31 15:30 UTC, HBuczynski commented on utils/senslog.c
> +	senslog_common.raw = false;
These variables equal `0` by default.

2022-10-31 15:30 UTC, HBuczynski commented on utils/senslog.c
> +	}
The `senslog_common.init` has the same value as `parse`.

2022-10-31 15:30 UTC, HBuczynski commented on utils/senslog.c
> + * extended kalman filter
You can change that it is a part of utility.

2022-10-31 15:30 UTC, HBuczynski commented on utils/Makefile
> +# This source code and Makefile is designed for compilation from _user directory of phoenix-rtos-project
Ups, it is not a `_user` directory.

2022-11-02 10:38 UTC, niewim19 commented on utils/senslog.c
> +		cnt += sprintf(&buf[cnt], "%lli.%06lli ", diff / 1000000, (diff - 1000000 * (diff / 1000000)));
Thanks, I missed that. Added logic for this error check (whole line is skipped if such error occurs)

2022-11-02 10:39 UTC, niewim19 commented on utils/senslog.c
> +	senslog_common.init = true;
As a matter of fact - no. I have removed it from the code and used value returned by `senslog_parseArgs` to indicate if application shall be stopped with or without an error.

2022-11-02 10:39 UTC, niewim19 commented on utils/senslog.c
> +	senslog_common.raw = false;
Yes, you`re right, it is not necessary. 

But in scope of this function imho it is more clear when it asserts correct initialization of parameters (`if` condition at the end of this function). If it is not against our coder style I would like to leave it as is.

2022-11-03 08:39 UTC, HBuczynski commented on utils/senslog.c
> +		if (senslog_common.flags.baro) {
There are separate conditions:
```suggestion
		}
		
		if (senslog_common.flags.baro) {
```

2022-11-03 08:39 UTC, HBuczynski commented on utils/senslog.c
> +				return +1; /* only help message printed, returning +1 */
```suggestion
				return 1; /* only help message printed, returning 1 */
```

2022-11-03 08:39 UTC, HBuczynski commented on utils/senslog.c
> +* +1 if only help was printed and application shall exit.
```suggestion
* 1 if only help was printed and application shall exit.
```

2022-11-03 08:39 UTC, HBuczynski commented on utils/senslog.c
> +	}
Applying this change, you will need to check only an `err` value in `95` line.
```suggestion
	if (devs == NULL || strlen(devs) == 0) {
		return -1;
	}
```

2022-11-03 09:15 UTC, niewim19 commented on utils/senslog.c
> +	}
Good idea! I have applied this check as separate if clause just below the highlighted one to be more secure (to not rely with condition output on conditions order)

2022-11-03 09:48 UTC, HBuczynski approved these changes

2022-11-03 09:59 UTC, merged