Add flight scenario parser
phoenix-pilot/phoenix-pilot-core pull request #172
Opened 2022-11-03 11:26 UTC by PNieck

## Description

This PR enables to parse flight scenario from file.

## Motivation and Context

We don't have to recompile program in order to change flight scenario.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-11-03 12:19 UTC, HBuczynski reviewed
I would change the name of this unit to `config`. It should parse the other files in the future as well.

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +static int invCnt;
To remove

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +#define INIT_SIZE 5
Used only in one place. Please remove.

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +} scenarioParser_common;
While data is parsed, you need to keep the pointer to data and size in a global variable. I suggest to make an array for each parser. 
This solution would not be thread safe.

```suggestion
enum { config_scenarioID = 0, config_pidID, config_end  };

static struct {
	void *result;
	size_t sz;  /* number of parsed data */
} res[config_end];
```

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +int quad_scenarioRead(flight_mode_t **scenario, const char *path)
I suggest to use convention, that the last arguments are the output args.

```suggestion
int quad_scenarioRead(const char *path, flight_mode_t **scenario, size_t *sz)
```

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +	return 0;
Repeated mistake.

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.c
> +	scenarioParser_common.result = malloc(sizeof(flight_mode_t) * INIT_SIZE);
Each of the config should have a specific init size.

2022-11-03 12:19 UTC, HBuczynski commented on quadcontrol/scenario_parser.h
> +#define FLIGHT_POSITION_LON    "lon"
To remove. It should not be a part of the API.

2022-11-03 14:27 UTC, HBuczynski commented on quadcontrol/config_parser.c
> +	config_end };
enum should be defined in one line

2022-11-03 14:27 UTC, HBuczynski commented on quadcontrol/config_parser.c
> +	}
`errno` should be checked after each conversion of string

2022-11-03 14:27 UTC, HBuczynski commented on quadcontrol/config_parser.c
> +		}
Missing assignment to `result`

2022-11-03 14:27 UTC, HBuczynski commented on quadcontrol/config_parser.c
> +	int err = 0, init_size = 5;
camelCase

2022-11-03 14:27 UTC, HBuczynski commented on quadcontrol/config_parser.c
> +	*sz = res[config_scenarioID].invCnt;
After that you can assign `NULL` to result.

2022-11-03 14:29 UTC, niewim19 commented on quadcontrol/config_parser.c
> +		tmp = realloc(res[config_scenarioID].result, sizeof(flight_mode_t) * ++res[config_scenarioID].sz);
Consider allocating surplus memory if we reach the current memory limit. Let`s say double the current limit, or 1,5 current limit.

2022-11-03 15:26 UTC, PNieck commented on quadcontrol/config_parser.c
> +	}
I have changed for checking `endptr` value - our implementation of `strto` functions don't set an `errno` in case of failure.

2022-11-03 15:29 UTC, PNieck commented on quadcontrol/config_parser.c
> +		tmp = realloc(res[config_scenarioID].result, sizeof(flight_mode_t) * ++res[config_scenarioID].sz);
I have changed for allocating space for 5 new elements.

2022-11-04 08:19 UTC, HBuczynski requested changes

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.c
> +	flight_mode_t *result = (flight_mode_t *)res[config_scenarioID].result;
You always point to the first element of the result. 
```suggestion
       unsigned int id = res[config_scenarioID].invCnt;
	flight_mode_t *mode = (flight_mode_t *)res[config_scenarioID].result[id];
```

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.c
> +static int config_takeoffParse(const hmap_t *h)
I would even add the second argument `flight_mode_t *mode` to point to the appropriate place in the array.

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.c
> +enum { config_scenarioID = 0, config_pidID, config_end };
To make a shorter references in the code:
```suggestion
enum { cfg_scenarioID = 0, cfg_pidID, cfg_end };
```

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.c
> +#define SCENARIO_MAX_FIELDS 3
Defines use only in one place, no need to make it public to other functions.

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.c
> +	int err = 0, initSize = 5;
```suggestion
	int err = 0;
	static const unsigned int initSz = 5;
```

2022-11-04 08:19 UTC, HBuczynski commented on quadcontrol/config.h
> + * Flight scenario parser
As above.

2022-11-04 11:30 UTC, PNieck commented on quadcontrol/config_parser.c
> +		tmp = realloc(res[config_scenarioID].result, sizeof(flight_mode_t) * ++res[config_scenarioID].sz);
Ok, I have done it same as you said

2022-11-04 13:11 UTC, HBuczynski requested changes

2022-11-04 13:11 UTC, HBuczynski commented on quadcontrol/control.c
> +static size_t scenarioSz;
You can move it to `quad_common`

2022-11-04 13:29 UTC, HBuczynski approved these changes
LGTM

2022-11-04 14:11 UTC, niewim19 reviewed
Looks good to me. Not giving approve as testing on drone will be done on Monday, but if everything goes well then it is only a matter of approve :)

2022-11-07 09:54 UTC, niewim19 approved these changes
Successfully tested on drone. I was able to modify scenario in runtime, not in compilation stage. Good job!

LGTM

2022-11-07 10:50 UTC, merged