Config parser
phoenix-pilot/phoenix-pilot-core pull request #176
Opened 2022-11-07 20:53 UTC by PNieck

## Description

This PR uses `parser` library to get PIDs and other configuration information from file.

## Motivation and Context

No code repetition. Two different modules don't do the same thing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
https://github.com/phoenix-pilot/phoenix-pilot-core/pull/175
- [ ] I will merge this PR by myself when appropriate.

2022-11-08 09:02 UTC, HBuczynski requested changes
The code in `control` looks much better after your changes.

General remark. Please provide the same API for all functions in `config.h`. If any changes in the future happens, handling it will be much easier.

A function in `config.h' should focus only on parsing dedicated structure, not the whole file. Making association with other headers within a file is not a good approach. The changes in parser library are necessary  to handle such situation.

2022-11-17 14:42 UTC, HBuczynski requested changes
General code looks fine.
I have pointed out some small remarks.

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/config.c
> +static int config_handleSpace(int parserType, size_t dataTypeSize)
`config_reallocStructs` or `config_reallocData` is more suitable.

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/config.c
> +static int config_adjustSpace(int parserType, size_t dataTypeSize)
`config_trimUnusedStructs` or `config_trimUnusedData`

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/config.c
> +	p = parser_alloc(1, 7);
Somme comment about `(1,7) magic numbers would be a good information`

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/config.c
> +
You can apply this for other functions:

```suggestion
*throttle = NULL;
*sz = 0;
```

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/config.h
> +/* Parser all PIDs from file defined by `path`. Returns array `pids` with length equal to `sz` */
Nope.
It returns 0 oraz -1.

2022-11-17 14:42 UTC, HBuczynski commented on quadcontrol/control.c
>  	}
`quad_init` function has become too big.
 I would suggest to put parsing logic in a `quad_config` functions.

2022-11-18 11:03 UTC, niewim19 submitted a review, later dismissed
LGTM

2022-11-18 11:15 UTC, PNieck commented
I have changed the name of define form `PATH_QUAD_CONFIG` to `PATH_QUAD_CONFIG`

2022-11-18 11:15 UTC, HBuczynski approved these changes
LGTM, nice improvement in quad-control unit.

2022-11-18 11:16 UTC, merged