pilot-core: automatic modes introduction
phoenix-pilot/phoenix-pilot-core pull request #184
Opened 2022-12-08 16:53 UTC by niewim19

## Description

Preliminary automatic modes introduction:
 - more modularized control module for easy RC override possibility
 - working implementation of `takeoff`, `hover` and `landing` procedure
 - changes of z accel bias estimation

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (zturn drone).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.
- [ ] - [ ]

2022-12-09 13:42 UTC, HBuczynski requested changes

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
>  #define RCTHRESH_LOW  ((5 * (MAX_CHANNEL_VALUE - MIN_CHANNEL_VALUE)) / 100 + MIN_CHANNEL_VALUE)  /* low position threshold */
I know that it is not a part of this PR, but you can add info that it is strictly related to channels
`RC_CHANNEL_THR_HIGH` & `RC_CHANNEL_THR_LOW`

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
> +static void quad_rcOverride(quad_att_t *att, float *throttle, uint32_t ovrdFlags)
```suggestion
static void quad_rcOverride(quad_att_t *att, float *throttle, uint32_t flags)
```

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
> +		att->yaw += (float)(rcYaw - ((MAX_CHANNEL_VALUE - MIN_CHANNEL_VALUE) / 2)) / 1000;
```suggestion
		att->yaw += (float)(rcYaw - ((MAX_CHANNEL_VALUE - MIN_CHANNEL_VALUE) / 2)) / 1000.f;
```

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
> +			quad_common.pids[pwm_alt].flags |= PID_IGNORE_P | PID_IGNORE_I | PID_IGNORE_D;
Please add a comment why you want to ignore PID

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
> +			setAlt = alt + 5000;
`5000` is a magic number

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.c
> +	const int32_t startAlt = -5000;                       /* starting with negative altitude to lower the throttle */
You can make `5000` as a define.

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.h
> +	int32_t liftTime;  /* time (milliseconds) to reach PID controlled throttle values */
Please use `time_t` and update parsing functions.

2022-12-09 13:42 UTC, HBuczynski commented on quadcontrol/control.h
> +	int32_t timeout; /* Time threshold of `diff` persistence to decide that landing is finished */
Please use `time_t`, update parsing functions and add units in the comment

2022-12-12 08:30 UTC, niewim19 commented
- added macros for magic numbers
- made time types consistent in using `time_t` type
- added necessary comments in conde

2022-12-12 09:46 UTC, HBuczynski commented on quadcontrol/control.c
> +	const float liftTime = mode->takeoff.liftTime;
Why `float` instead of `time_t`?

2022-12-12 09:58 UTC, HBuczynski approved these changes
LGTM

2022-12-12 09:59 UTC, merged