quad-control: pid attenuation and log dropping
phoenix-pilot/phoenix-pilot-core pull request #193
Opened 2023-02-02 18:58 UTC by niewim19

## Description

Two changes in this PR:
 - partially dropping logging of quad-control as it is less usable now and takes time to print (lowers loop efficiency)
 - implementing pid attenuation:
   - pid values attenuation happens accordingly to attenuation factor
   - pid values are straight multiplied by attenuation factor
   - attenuation factor is calculated based on current throttle and attenuation factor curve specified by user
   - attenuation factor curve has 3 points:
     1) at throttle equal 0 and of `startVal` value
     2) at throttle equal `startVal` and of `startVal` value
     3) at throttle equal 1 and of `startVal` value 

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: zturn drone.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2023-02-06 19:09 UTC, kemonats commented on quadcontrol/config.c
> +	static const unsigned int initSz = 1;
```suggestion
	const unsigned int initSz = 1;
```
`static` is no needded

2023-02-15 16:36 UTC, niewim19 commented
@PNieck Could you please take a look at the parser modifying commit?

2023-02-16 07:52 UTC, PNieck commented
> @PNieck Could you please take a look at the parser modifying commit?

Sure

2023-02-16 08:46 UTC, PNieck requested changes

2023-02-16 08:46 UTC, PNieck commented on quadcontrol/config.h
> +Returns -1 on error ir multiple attenuation structures.
Typo - `ir` should be `or`
```suggestion
Returns -1 on error or multiple attenuation structures.
```

2023-02-16 08:46 UTC, PNieck commented on quadcontrol/config.c
> +int config_attenRead(const char *path, mma_atten_t **atten, int *sz)
I don't see where `conf_attenRead` returns `-1` in case of multiple attenuation structures, as in described in `config.h`

2023-02-16 08:46 UTC, PNieck commented on quadcontrol/config.h
> +Returns -1 on error ir multiple attenuation structures.
I am suggesting to remove returning `-1` in case of multiple attenuation structures. There were are only reading configuration files. Logic of checking if this configuration is valid is in `control.c` file in `quad_config` function.

2023-02-16 11:02 UTC, niewim19 commented on quadcontrol/config.h
> +Returns -1 on error ir multiple attenuation structures.
Removed this line from function description

2023-02-16 11:03 UTC, niewim19 commented on quadcontrol/config.c
> +int config_attenRead(const char *path, mma_atten_t **atten, int *sz)
Removed this line from function description in config.h

2023-02-16 11:04 UTC, niewim19 commented on quadcontrol/config.c
> +	static const unsigned int initSz = 1;
Leaving it with static. All other parsers have this variable as `static const unsigned int` so that would be an issue to address in separate PR.

2023-02-16 11:58 UTC, PNieck requested changes

2023-02-16 13:20 UTC, niewim19 commented on quadcontrol/config.c
> +	*sz = 0;
Good idea, implemented. Thanks!

2023-02-16 15:29 UTC, PNieck approved these changes
LGTM

2023-02-22 15:44 UTC, merged