Ekf config parser update
phoenix-pilot/phoenix-pilot-core pull request #201
Opened 2023-03-10 11:02 UTC by PNieck

## Description

This PR changes how the configuration files are read. Now parser library is used.

## Motivation and Context

1. Removing old temporary solution.
2. Making config reads more consistent

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-03-12 16:21 UTC, niewim19 requested changes
Initially it was assumed that a separate file for field interpreting functions would be needed. As it turns out this does not need so much code so I think it may be bundled into one function and put into the `parser.c` file.

2023-03-12 16:21 UTC, niewim19 commented on libs/parser/parser.h
> +extern int parser_fieldParseHelper(const hmap_t *h, const char *fieldName, void *target, parser_fieldType fieldType);
This function is ought to be used inside converters - please mention it in the comment

2023-03-12 16:21 UTC, niewim19 commented on ekf/kalman_implem.c
> +	err |= parser_headerAdd(p, "LOGGING", kmn_loggingConverter);
Just an idea for the future:

parser_headerAdd can accept a void pointer that will be passed to converters as target space to write out data. This way parser would be more thread safe as now it heavily rely on common structures to write out data.

2023-03-12 16:21 UTC, niewim19 commented on ekf/kalman_implem.c
> +	err |= parser_fieldParseHelper(h, "P_rerr", &converterResult->P_rerr, parser_float);
As we discussed the prefix `P_`/`Q_` may be dropped in the config file. The header specifies the context.

2023-03-12 16:21 UTC, niewim19 commented on ekf/kalman_implem.h
> +extern int kmn_configRead(const char *configFile, kalman_init_t *initVals);
```suggestion
/* Function reads ekf configuration file under `path` and fills structure pointed by `initVals`  */
extern int kmn_configRead(const char *path, kalman_init_t *initVals);
```

2023-03-13 09:41 UTC, PNieck commented on libs/parser/converter_helpers.c
> +union parser_target {
When I use `static` I get `useless storage class specifier in empty declaration` compilation error

2023-03-13 10:00 UTC, PNieck commented on ekf/kalman_implem.c
> +	err |= parser_headerAdd(p, "LOGGING", kmn_loggingConverter);
Good idea, I have saved it in issue connected with parser refactoring

https://github.com/phoenix-pilot/phoenix-pilot-core/issues/197

2023-03-13 11:25 UTC, niewim19 reviewed
Only one small change and lets go

2023-03-13 11:25 UTC, niewim19 commented on libs/parser/parser.c
> +
Please add NULL check for `target`

2023-03-13 17:12 UTC, kemonats commented on libs/parser/parser.c
> +
And maybe aligning the `target` address to 4

2023-03-15 10:55 UTC, PNieck commented on libs/parser/parser.c
> +
@kemonats You mean checking if `target % 4 == 0`, am I right?

2023-03-17 11:12 UTC, PNieck commented on libs/parser/parser.c
> +
Done. I have fixed as the @agkaminski suggested.

2023-03-17 14:45 UTC, merged