Update config parsing in quadcontrol
phoenix-pilot/phoenix-pilot-core pull request #209
Opened 2023-03-27 11:57 UTC by PNieck

## Description

This PR updates config parsing so it's using newly added functions.

## Motivation and Context

'
Smaller redundancy in code

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-03-27 19:19 UTC, niewim19 requested changes

2023-03-27 19:19 UTC, niewim19 commented on libs/parser/parser.c
> +	*target = strtol(valueStr, &endptr, 10);
`time_t` is of size `unsigned long long`, `strtoull` should be used.

2023-03-28 07:42 UTC, kemonats commented on libs/parser/parser.c
> +
I suggest converting to a temporary variable and writing to the `target` variable it there is no error.
You can then set the default value before calling `parser_fieldGetTime()`.
Same in the `parser_fieldGetInt()`.
```suggestion
	time_t t;
	t = strtoull(valueStr, &endptr, 10);

	if (*endptr != '\0') {
		fprintf(stderr, "%s: cannot parser value of \"%s\" - %s - to int.\n", __FUNCTION__, fieldName, valueStr);
		return -1;
	}
	*target = t;

```

2023-03-29 16:27 UTC, niewim19 approved these changes
LGTM

2023-03-29 21:33 UTC, merged