Add tests for `qvdiff_qpDiffP` function
phoenix-pilot/phoenix-pilot-core pull request #220
Opened 2023-04-19 11:40 UTC by PNieck

## Description

Adding unit tests of one of the functions from quaternion derivatives library.

## Motivation and Context

More robust interface for algebra library.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu` `hostgeneric-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2023-04-19 20:35 UTC, niewim19 requested changes

2023-04-19 20:35 UTC, niewim19 commented on algebra/tests/qdiff/tests.c
> +		algebraTests_createAndFill(&M, ROWS, COLS_VEC_DIFF, matInitBuff, BUFFILL_WRITE_ALL));
In all tests `M` is heavily modified from the start and always it is evaluated to some non-zero matrix. Usage of `algebraTests_createAndFill` may suggest that it is important for us to fill it with `matInitBuff`, but really it is not. Pure `matrix_bufAlloc` will do the job. It also `calloc`s the memory so we are sure it is zero-filled from the beginning. I think this applies to both `qvdiff_qpDiffP` (just added) and `qvdiff_qpDiffQ` (added previously)

2023-04-19 20:35 UTC, niewim19 commented on algebra/tests/qdiff/tests.c
> +	algebraTests_transposeSwap(&M);
Is contents swap necessary? If not, `matrix_trp()` may also do the job.

2023-04-19 20:35 UTC, niewim19 commented on algebra/tests/qdiff/tests.c
> +	TEST_ASSERT_NOT_EQUAL(0, qvdiff_qpDiffP(&A, &M));
If this matrix is allocated in SETUP fixtures, let`s not deallocate it in test body if not necessary. A local matrix may be statically defined with static buffer and you can just mingle with rows/cols parameters (just declare it a little too big)

2023-04-21 08:15 UTC, PNieck commented on algebra/qdiff.c
> +		out->rows = tmp;
It is necessary, because if matrix is transposed and passed through size check, when `M->rows = 3` and `M->cols = 4`, because transposition operation changes only the transposition flag. Without switching we get matrix with wrong size,

2023-04-21 08:19 UTC, PNieck commented on algebra/tests/qdiff/tests.c
> +	algebraTests_transposeSwap(&M);
Matrix `M` in these tests is not a square matrix, so if a just transpose it, then it has wrong size - not $4\times 3$, but $3 \times 4$

2023-04-21 08:49 UTC, PNieck commented on algebra/tests/qdiff/tests.c
> +	TEST_ASSERT_NOT_EQUAL(0, qvdiff_qpDiffP(&A, &M));
I have changed allocation of this matrix to statically allocated. After this PR I can make another one thie changes to previous `qdiff` tests

2023-04-25 08:12 UTC, niewim19 commented on algebra/tests/qdiff/tests.c
> +	M.cols = COLS_VEC_DIFF;
As I see this is an outcome of my previous remark about static declaration of matrix if its sizes are about to be changed. What i meant was:
 - use dynamically allocated M from TEST_SETUP where it is used as is (in terms of its sizes and memory)
 - use statically allocated matrix (other than M) in test which needs to change size of this matrix

and by static allocation I meant memory static allocation inside test body (in the scope of one test, not the whole file. Both are static though, so sorry for not being precise) With current solution `buff1` and `buff2` are globally allocated during all test executions (no matter which group of test is run) which just bloats the memory.

Thinking in scope of memory usefulness its good to try to predict how often the memory will be used and chose proper allocation type. If memory will be used for a short period of time it is usually best to allocate it locally. In this scope matrix `M` is statically allocated in scope of the file as it is reused very often. Data memory of this matrix is often changed (its size changes between test groups) so it is dynamically allocated for each test in TEST_SETUP.
Please follow the allocation style from `group_qvdiff_qpDiffQ` for matrix `M` and `Expected` and use test-scope matrices in `qvdiff_qpDiffP_wrongOutputMatrixSize` where the sizes are modified.

2023-04-25 08:12 UTC, niewim19 commented on algebra/tests/qdiff/tests.c
> +		algebraTests_createAndFill(&M, ROWS_QUAT_DIFF, COLS_QUAT_DIFF, matInitBuff, BUFFILL_WRITE_ALL));
Why not:
```suggestion
TEST_ASSERT_EQUAL(MAT_BUF_ALLOC_OK, matrix_bufAlloc(&M, ROWS_QUAT_DIFF, COLS_QUAT_DIFF));
```

2023-04-28 07:12 UTC, niewim19 approved these changes
LGTM

2023-04-28 07:13 UTC, merged