scripts: add live log plotting utility
phoenix-pilot/phoenix-pilot-core pull request #23
Opened 2022-07-08 11:20 UTC by niewim19

JIRA: PP-49

## Description

## Motivation and Context

Live plotting AHRS data during tests with python script that reads logs from serial port. pyqtplot library used.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-07-14 15:23 UTC, jsarzy requested changes
Nice looking tool! It would be nice to keep good quality code if we want to make this tool reusable, so I pointed few things .

I also encourage you to use formatting tools like `black`.

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +    global PLOTCUT, PWM_LOW
Maybe just structure code to not using globals

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +ser = serial.Serial(PORTPATH, baudrate=115200, timeout=1)
Maybe pack it into `try: except SerialException:` in case of bad port or something

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +    global e, p2, elines
maybe structure code to not use globals, should be easy in this case

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +win = pg.GraphicsLayoutWidget(show=True, title="Phoenix-pilot logging tool")
maybe pack these init statements in some god named functions (or even a class).

Below example:
```python
gui = Gui() # here plots are initialized
# and then we can
line = ser.readline()
data = parse_data(line)
gui.update(data)

# example methods that gui can offer
gui.update_pid_plot(data)
gui.update_roll_pitch_plot(data)
etc...
```

2022-07-14 15:23 UTC, jsarzy commented on scripts/README.md
> +# quadLive.py plotting utility
add requirements.txt

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +import numpy as np
do we use these imports?

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +from sqlalchemy import except_all
do we use this import?

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +win.setWindowTitle('Phoenix-pilot logging tool')
Be consistent and use "" everywhere

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +win.resize(1500,800)
add space

2022-07-14 15:23 UTC, jsarzy commented on scripts/quadLive.py
> +                        e[i].append(float(ls[i+2]))
I don't know what `setData` api requires, but if it's `Iterable` (without indexes) then we could use `collections.deque` here. This allows us to perform popleft (here `pop(0)`) operations in time O(1) instead of O(n). I know probably it doesn't matter here but is good practice :)

2022-07-15 07:41 UTC, niewim19 commented on scripts/quadLive.py
> +                    None
I went for:
```python
try:
(...)
except:
pass
```
as this script may run on wireless connection with little transmission correction protocols and different errors may occur, as some letters may disappear. But you are right that some errors may be difficult to pinpoint with such approach.

2022-07-15 07:42 UTC, niewim19 commented on scripts/quadLive.py
> +    global PLOTCUT, PWM_LOW
Yea - this is a good idea. Went for much more object oriented code.

2022-07-15 07:44 UTC, niewim19 commented on scripts/quadLive.py
> +                        e[i].append(float(ls[i+2]))
This is the only thing I have left untouched. I would like to do it in next refactoring step

2022-07-15 07:49 UTC, niewim19 commented
@jsarzy Thank you for your thorough review. I have restructured code so that almost none of it is in the lowest level of script. Also used argparse as you mentioned and added `requirements.txt` file (there is neat tool `pipreqs` for that)

One important thing you pointed - the use of arrays instead of queues - was left untouched, as I would like to do it in later stages.

2022-08-23 14:29 UTC, jsarzy submitted a review, later dismissed

2022-09-02 10:34 UTC, niewim19 commented
After jsarzy review minor changes were made to this branch:
 - changing variable names to be more meaningful and consistent across different plots
 - swap roll/pitch plot with yaw plot so that they are above corresponding pid plots
 - rebas onto current main

2022-09-02 10:38 UTC, damianloew approved these changes

2022-09-02 10:40 UTC, merged