Change logging logic
phoenix-pilot/phoenix-pilot-core pull request #238
Opened 2023-06-14 11:09 UTC by PNieck

## Description

This PR changes how pilot collects logs.
- Different logic of specifying what to log. Now what to log is specified by names not number. Moreover user can specify precisely what to log by writing down all logging targets separated with commas.
- Logic of collecting logs is not asynchronous

## Motivation and Context

Faster and more flexible way of collecting logs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-vpilot`, `host-generic-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-06-15 06:27 UTC, niewim19 requested changes
Well designed. My remarks mostly address simplifying the producer-consumer scheme in buffer access.

2023-06-15 06:27 UTC, niewim19 commented on ekf/log.c
> +		}
Can `nextMsg`-`tail`-`head` logic be done without `nextMsg`? What we actually care is next nul character, head and tail. Logging thread reads from current thread up to the first nul character, updates head (and if possible rewinds to buffer beginning). Writing thread appends new message to buffer (if sufficient space is available, only updates tail.

2023-06-15 06:27 UTC, niewim19 commented on ekf/log.c
> +	while (true) {
This while loop can be conditioned using `ekflog_common.run` variable. This way you will avoid infinite loop. This may require making this variable `volatile`.

2023-06-20 13:10 UTC, niewim19 requested changes
Left some remarks after fixes. Why can`t we use one log flag to store the strict paramater (like all other flags). Just exclude it from `all` flags.

2023-06-21 09:20 UTC, PNieck commented on ekf/log.c
> +	if (pthread_attr_setschedparam(&attr, &sched) != 0) {
Other operating systems can have different range of possible priorities.  So I have decided to set thread priority only on main system - phoenix

2023-06-21 09:44 UTC, PNieck commented on ekf/log.c
> +			if (fputs(&ekflog_common.queue[ekflog_common.tail], ekflog_common.file) <= 0) {
But we don't know the exact length of a message

2023-06-21 09:58 UTC, PNieck commented on ekf/log.c
>  		if ((ekflog_common.mode & EKFLOG_STRICT_MODE) != 0) {
Do you mean `vfprintf` function and not using separate thread?

2023-06-21 12:38 UTC, niewim19 commented on ekf/kalman_implem.c
> +		}
ALL triggers STRICT

2023-06-21 12:38 UTC, niewim19 commented on ekf/log.c
> +	int queueEnd;
Return to buff

2023-06-21 12:38 UTC, niewim19 commented on ekf/log.c
> +#endif
ifdef `in situ`

2023-06-23 13:27 UTC, niewim19 approved these changes

2023-06-23 13:33 UTC, merged