calib: axis swapping in `accorth`
phoenix-pilot/phoenix-pilot-core pull request #239
Opened 2023-06-15 06:58 UTC by niewim19

## Description

Addition of axis swapping/inversion solution in IMU initial rotation estimation. From now on measurements of IMU are not only rotated using quaternion but also their order is switched and inverted if necessary. 

## Motivation and Context

Estimating IMU rotation only with quaternion has a room for an error if that rotation is big/complex (not along one axis). Instead of using only quaternion it may be easier to firstly switch axis order and/or invert some of them and then calculate the quaternion. 

This way big rotations are not included in the quaternion so it more correctly estimates the missalignment of the axis. This also makes the calibration procedure more robust i.e. differences between consecutive calibration procedures in calibtool produce more similar calibration parameters. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: zturn drone.

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2023-06-16 10:05 UTC, PNieck requested changes

2023-06-16 10:05 UTC, PNieck commented on libs/calib/calib.h
> +			accSwap_t swapOrder; /* axis swap order: e.g 312 means that [x,y,z] will be read as [z, x, y] */
Misleading comment, which suggest that you are using tree digit numbers to remember swap order, when in reality program uses enum values

2023-06-16 10:05 UTC, PNieck commented on calib/accorth.c
> +	 * Axis switching search is done by bruteforcing all combinations, 24 total.
If my calculations are correct there are 48 combinations. You can order arises in 6 ways and then negate them or not in 8 ways.

2023-06-16 10:24 UTC, niewim19 commented on calib/accorth.c
> +	 * Axis switching search is done by bruteforcing all combinations, 24 total.
Yes, there are 48 arbitrary combinations, but only half of them follow the right-hand rule.

2023-06-16 10:38 UTC, PNieck commented on calib/accorth.c
> +	 * Axis switching search is done by bruteforcing all combinations, 24 total.
Yes, you are right

2023-06-16 10:39 UTC, PNieck commented on calib/accorth.c
> +	 * Axis switching search is done by bruteforcing all combinations, 24 total.
```suggestion
	 * Axis switching search is done by brute forcing all right-hand combinations, 24 total.
```

2023-06-19 09:57 UTC, PNieck requested changes

2023-07-10 13:23 UTC, niewim19 commented on libs/calib/calib.h
> +#define ACC_CHAR_SWAP_SIGN 's'
They will be in different positions in line. `ACC_CHAR_SWAP` occupies index 0, and `ACC_CHAR_SWAP_SIGN` occupies index 1.

Final form in `calib.conf`: https://github.com/phoenix-pilot/phoenix-pilot-project/blob/acd1b2fa91288173cf1933b5186f953e7a77f6ab/_projects/armv7a9-zynq7000-pilot/rootfs-overlay/etc/calib.conf#L12-L32

2023-07-10 13:23 UTC, niewim19 commented on calib/accorth.c
> +				imLen = sqrt(q.i * q.i + q.j * q.j + q.k * q.k);
Yeah, good idea, but as you mentioned - this is not performance-intensive code. I would rather stay with `sqrt` as to make it easy to see in the coda what is happening.

2023-07-10 14:16 UTC, PNieck commented on libs/calib/calib.h
> +			accSwap_t swapOrder; /* axis swap order: e.g 312 means that [x,y,z] will be read as [z, x, y] */
This issue is still not fixed

2023-07-11 09:53 UTC, niewim19 commented on libs/calib/calib.h
> +			accSwap_t swapOrder; /* axis swap order: e.g 312 means that [x,y,z] will be read as [z, x, y] */
Thanks! Updated.

2023-07-11 10:57 UTC, PNieck approved these changes
LGTM

2023-07-11 10:59 UTC, merged