Logs converter
phoenix-pilot/phoenix-pilot-core pull request #245
Opened 2023-07-24 14:59 UTC by PNieck

## Description

PR contains script to convert logs form binary forma to `csv` and the other way around.

## Motivation and Context

Easier logs manimulation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `host-generic-pc`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2023-07-24 15:03 UTC, PNieck commented
Codespell is not recognizing `ned` keyword.

2023-07-26 13:10 UTC, niewim19 requested changes

2023-07-26 13:10 UTC, niewim19 commented on scripts/logs/common/formats/binary/bin_parser.py
> +            z=self.__parse_field(file, field)
nitpic: no spaces around `=`

2023-07-26 13:10 UTC, niewim19 commented on scripts/logs/common/formats/binary/bin_export.py
> +        self.fields_specifiers = FIELDS
The same idea as in `bin_parser.py` about direct `FIELDS.ger("acceleration")` usage

2023-07-26 16:56 UTC, PNieck commented on scripts/logs/common/formats/binary/bin_parser.py
> +            z=self.__parse_field(file, field)
Yes, but according to our Python codding conventions we don't use spaces around `=`, when it comes to function arguments.

2023-07-31 10:39 UTC, niewim19 commented on scripts/logs/common/formats/binary/bin_parser.py
> +            z=self.__parse_field(file, field)
Yeah, missed that. Remark is invalid :)

2023-07-31 10:44 UTC, niewim19 approved these changes
Very nicely written, good job!

2023-07-31 11:42 UTC, merged