Change logs to binary
phoenix-pilot/phoenix-pilot-core pull request #248
Opened 2023-07-31 09:08 UTC by PNieck

## Description

PR changes type of logs to binary one.

## Motivation and Context

- faster logging
- more compact result files with logs

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-08-01 07:46 UTC, niewim19 requested changes
Remarks refer only to `ekf/log.c` file. Rest of the PR looks well.

2023-08-01 07:46 UTC, niewim19 commented on ekf/log.c
> +	char msg_buff[MAX_MSG_LEN];
How about dropping the one buffer approach and moving it into `buff_part_t`? Initialization would not require sectioning of the main buffer and only one macro `BUFF_LEN` would be needed

2023-08-01 07:46 UTC, niewim19 commented on ekf/log.c
> +	ekflog_common.parts[1].size = 0;
In some parts of code it looks like the number of parts is easily changeable with the macro value, but here the initialization is fixed to 2. As we want to have only 2 parts, lets call them `buffA` and `buffB` and initialize them accordingly and drop their arrayization as much as possible. 

Also it would shorten the names as now there is `buff`, `buffPart` and `actBuffPart`.

2023-08-01 11:32 UTC, niewim19 requested changes

2023-08-01 11:32 UTC, niewim19 commented on ekf/log.c
> +extern int ekflog_senscImuWrite(const sensor_event_t *accEvt, const sensor_event_t *gyrEvt, const sensor_event_t *magEvt)
This function, and those similar to it (other logtypes) can instantiate their own buffers locally of `MAX_MSG_LEN` size. Access to common `ekflog_common.msg_buff` is not necessary and is not thread safe.

2023-08-01 11:32 UTC, niewim19 commented on ekf/log.c
> +	ekflog_addLogField(ekflog_common.msg_buff, &msg_len, &accEvt->accels.accelX, sizeof(accEvt->accels.accelX));
If you redesign `ekflog_addLogField()` so that it only accepts `char ptr, const void *data, size_t n` and returns the `n` you can omit multiple data passes in function calls:

```suggestion
	char buff[MAX_MSG_LEN];
	char *msgHead = buff;

	msgHead += ekflog_addLogField(msgHead, &accEvt->accels.accelX, sizeof(accEvt->accels.accelX));
```

2023-08-01 11:32 UTC, niewim19 commented on ekf/log.c
> +	printf("Lost logs: %d\n", ekflog_common.lost);
This may be moved to the end of the thread, after it escapes the `while` loop. As logging ends with the thread, there might be a good place to print info. Do as you wish :)

2023-08-01 15:41 UTC, PNieck commented on ekf/log.c
> +	ekflog_common.actBuff->size += msg_len;
Yes you are right

2023-08-01 15:46 UTC, PNieck commented on ekf/log.c
> +		while (outBuff->dirty == true) {
If writing to file is slow enough, then writer can make the second buffer dirty while the first one is being cleaned by thread. After such an incident program ends up one buffer always dirty.

2023-08-02 08:28 UTC, kemonats commented on ekf/log.c
> +	char buff[BUFFS_CAPACITY];
If binary it would be better
```c
	unsigned char buff[BUFFS_CAPACITY];
or
	uint8_t buff[BUFFS_CAPACITY];

2023-08-02 08:29 UTC, kemonats commented on ekf/log.c
> +static int ekflog_writeLogPrefix(char *msg_buf, char msgType, time_t timestamp)
```suggestion
static size_t ekflog_writeLogPrefix(char *msg_buf, char msgType, time_t timestamp)
```

2023-08-02 08:29 UTC, kemonats commented on ekf/log.c
> +	return sizeof(uint32_t) + sizeof(char) + sizeof(uint64_t);
consistently
```suggestion
	return sizeof(ekflog_common.logCnt) + sizeof(msgType) + sizeof(time);
```

2023-08-02 08:29 UTC, kemonats commented on ekf/log.c
> +	memcpy(&msg_buf, data, dataSize);
```suggestion
	memcpy(msg_buf, data, dataSize);
```

2023-08-02 08:29 UTC, kemonats commented on ekf/log.c
> +extern int ekflog_timeWrite(time_t timestamp)
`extern` redundant, also with other functions
```suggestion
int ekflog_timeWrite(time_t timestamp)
```

2023-08-02 10:19 UTC, PNieck commented on ekf/log.c
> +extern int ekflog_timeWrite(time_t timestamp)
We are using `extern` in all other header file, so for consistency I leave as it is

2023-08-02 12:15 UTC, niewim19 approved these changes
LGTM

2023-08-02 12:55 UTC, merged

2023-08-14 09:15 UTC, PNieck commented on ekf/log.c
> +extern int ekflog_timeWrite(time_t timestamp)
Ok, I agree. That's my fault. Fixed in separate PR -> https://github.com/phoenix-pilot/phoenix-pilot-core/pull/251