Logs analysis
phoenix-pilot/phoenix-pilot-core pull request #249
Opened 2023-07-31 12:13 UTC by PNieck

## Description

PR adds simple script for logs analysis. It enables to:
- check for missing logs
- check time of ekf loops
- check what types of logs was saved in this file

## Motivation and Context

Faster logs analysis

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `host-generic-pc`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-08-01 10:37 UTC, niewim19 requested changes
I suggest joining files `analysis.py` and `analysis_factory` into one, and either:
 - merge analysis classes into one file
 - moving them to separate module. Then in factory you will only do `import analyses` and then list them in as `analyses.logsCnt` etc.

2023-08-01 10:37 UTC, niewim19 commented on scripts/logs/analyse_logs.py
> +        analysis.run(analyses_context)
This is somewhat silly remark, but let's try to avoid multiple form of `analyses` in the code as they blend together and their abbreviation is... somewhat not usable in code :P

Consider the following ideas:
```suggestion
    handler = FormatFactory.from_path(args.log_file)
    logs = handler.import_logs(args.log_file)
    ctx = StudyContext(logs)

    for s in StudyFactory.get_studies():
        s.run(ctx)
```

or

```suggestion
    handler = FormatFactory.from_path(args.log_file)
    logs = handler.import_logs(args.log_file)
    ctx = DataContext(logs)

    for e in EvalFactory.get_studies():
        e.run(ctx)
```

also possible: jobs, tasks, scans etc.

2023-08-01 10:37 UTC, niewim19 commented on scripts/logs/logs_analysis/context.py
> +        filler = AnalysisContext.ContextFiller(self)
`filler` may be a class level attribute as it will be shared across all instances of context class

2023-08-01 10:37 UTC, niewim19 commented on scripts/logs/logs_analysis/context.py
> +    def get_index_from_all_logs(self, log: log_types.LogReading) -> int:
Name shortening idea:
```suggestion
    def get_indices(self, log: log_types.LogReading) -> int:
```

please add a docstring what it does

2023-08-01 10:37 UTC, niewim19 commented on scripts/logs/logs_analysis/context.py
> +    def __calculate_missed_logs_cnt(self) -> int:
```suggestion
    def get_missed(self, index: int) -> int:
        if index == 0:
            return self.all_logs[index].id - 1
        else:
            return self.all_logs[index].id - self.all_logs[index - 1].id - 1

    def __calculate_missed(self) -> int:
```

2023-08-01 12:09 UTC, PNieck commented on scripts/logs/analyse_logs.py
> +        analysis.run(analyses_context)
I have chosen `evaluations`

2023-08-01 12:12 UTC, PNieck commented
Factory is still in separate file. If I merge them, then circular import problem raises

2023-08-02 06:44 UTC, niewim19 approved these changes
Nicely reuses code of log parser. Looks good to me.

2023-08-02 09:21 UTC, merged