Add polling error flag
phoenix-pilot/phoenix-pilot-core pull request #265
Opened 2023-08-30 14:34 UTC by PNieck

## Description

Add ekf error reporting

## Motivation and Context

Possibility not to ignore possible EKF errors.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-09-05 11:59 UTC, niewim19 requested changes
Looks good. General remarks:
 - if `errno` is extensively used, we can signal _all good_ with EOK, as it is part of errno interface,
 - let's think about single ekf breking point - currently each data polling can break the ekf loop (stop it) separately. As that loop has clearly _data getting_ part and _math part_ it may be possible to poll whatever is needed and break the loop in between these parts if necessary to de-clutter the code out of `return`s.

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +	errno = 0;
```suggestion
	errno = EOK;
```

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +		ekf_common.status |= errno == 0 ? EKF_MEAS_EOF : EKF_ERROR;
```suggestion
		ekf_common.status |= (errno == EOK) ? EKF_MEAS_EOF : EKF_ERROR;
```

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +		if (ekf_common.initVals.measSource == srcLog) {
Add a suitable comment here, please

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +			ekf_common.status |= errno == 0 ? EKF_MEAS_EOF : EKF_ERROR;
```suggestion
			ekf_common.status |= (errno == EOK) ? EKF_MEAS_EOF : EKF_ERROR;
```

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +			ekf_common.status |= errno == 0 ? EKF_MEAS_EOF : EKF_ERROR;
```SUGGESTION
			ekf_common.status |= (errno == EOK) ? EKF_MEAS_EOF : EKF_ERROR;
```

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +				ekf_common.status |= errno == 0 ? EKF_MEAS_EOF : EKF_ERROR;
```SUGGESTION
				ekf_common.status |= (errno == EOK) ? EKF_MEAS_EOF : EKF_ERROR;
```

2023-09-05 11:59 UTC, niewim19 commented on ekf/ekflib.c
> +				ekf_common.status |= errno == 0 ? EKF_MEAS_EOF : EKF_ERROR;
```SUGGESTION
				ekf_common.status |= (errno == 0) ? EKF_MEAS_EOF : EKF_ERROR;
```

2023-09-05 11:59 UTC, niewim19 commented on utils/devekf.c
> +		printf("EKF: meas module encountered EOF");
Why we do not halt `devekf` on EOF?

2023-09-05 12:18 UTC, PNieck commented on ekf/logs/reader.c
> +	errno = 0;
`EOK` is not available on host

2023-09-05 12:25 UTC, PNieck commented
I cannot use `EOK`, because it is not available on host

2023-09-05 12:48 UTC, niewim19 commented
> I cannot use `EOK`, because it is not available on host

Ok, if so then `0` is ok.

2023-09-06 08:54 UTC, niewim19 requested changes

2023-09-06 08:54 UTC, niewim19 commented on ekf/ekflib.c
> +	bool dataAcqSucc;
Slight modification for more appropriate name ;)
```suggestion
	bool dataAcqOk;
```
On the other hand `ekf_common.run` may be used for this purpose: just set this variable to false in `*Acq()` ladder and then before math part there is check if we still want to run the loop.

2023-09-06 08:54 UTC, niewim19 commented on ekf/ekflib.h
> +#define EKF_ERROR          (1 << 1)
```suggestion
#define EKF_ERROR          (1 << 1) /* general purpose error flag */
```

2023-09-13 08:05 UTC, niewim19 approved these changes

2023-09-13 08:48 UTC, merged