pilot-core: imu temperature calibration
phoenix-pilot/phoenix-pilot-core pull request #266
Opened 2023-09-01 09:09 UTC by niewim19

## Description

 - adding imu temperature calibration `tempiumu`
 - correction module more modular
 - correction module initialization flags

## Motivation and Context

Adding `tempimu` calibration type forced a change in `sensc` and `corr` so that it is possible to run only selected calibrations and corrections. It is because `tempimu` calibration must be applied on non-calirbated data and current `accorth` calibration must be done on `tempimu` calibrated data, yet it is no possible to do these calibrations together. 

This problem occurs also with `magiron`/`magmot` calibrations and `accorth`/`accrot` but there it was mitigated by joining calibration procedures. However to tidy it up these calibrations will need splitting and the correct order of calibration enforced in `calibtool` with `corrInitFlags`.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: zturn drone

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-10-02 10:54 UTC, PNieck requested changes

2023-10-02 10:54 UTC, PNieck commented on calib/tempimu.c
> +	if (tempimu_imuAvg(DATA_POINT_SAMPLES_PERIOD_US * 2, DATA_POINT_SAMPLES_PERIOD_US, &accelEvt, &gyrEvt) != 0) {
Why are you using samples period, where samples count should be passed it's missleading

2023-10-02 10:54 UTC, PNieck commented on calib/tempimu.c
> +static int tempimu_imuAvg(unsigned int samples, time_t usDelay, sensor_event_t *accOut, sensor_event_t *gyrOut)
You are calculating average value of all accelerometer and gyroscope data, but only temperature is used. Maybe rename this function to `tempimu_imuAvgTemp` and return only temperature.

2023-10-02 11:11 UTC, PNieck requested changes

2023-10-02 11:11 UTC, PNieck commented on calib/gyrorth.c
> +	printf("Calibration done!");
Add message, that this form of calibration is not working for now

2023-10-02 11:38 UTC, niewim19 commented on libs/calib/calib.c
Added type setup in `calib_readFile()`

2023-10-02 11:38 UTC, niewim19 commented on libs/calib/calib.c
> +	cal->params.tempimu.alfaGyr[2] = 0;
Added comment about calibration process and default values

2023-10-02 11:39 UTC, niewim19 commented on libs/calib/calib.c
>  			return;
Split into all non-allocating types, and `default` with error message.

2023-10-02 11:46 UTC, niewim19 commented on libs/sensc/sensc.c
> +		corr_magmot(magEvt);
This is heavily amended in future commits.

2023-10-03 08:36 UTC, niewim19 commented on libs/sensc/sensc.c
>  		if (corr_init(CORR_ENBL_ALL) != 0) {
This is added later in the commits. At this point the goal was to use any flag as it was not fully implemented yet.

2023-10-03 08:47 UTC, niewim19 commented on calib/tempimu.c
> +static int tempimu_imuAvg(unsigned int samples, time_t usDelay, sensor_event_t *accOut, sensor_event_t *gyrOut)
You pointed correctly - there is discrepancy between the name of function, its description and its usage. 

However this function is used both for temperature and imu readings. So it does average over imu measurements, together with temperature. I would stay with `tempimu_imuAvg`.

2023-10-03 09:25 UTC, merged