EKF state logging
phoenix-pilot/phoenix-pilot-core pull request #269
Opened 2023-09-13 09:01 UTC by PNieck

## Description

This PR add ability to log EKF state during every iteration

## Motivation and Context

Easier debugging and testing

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `host-generic-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-09-14 10:24 UTC, niewim19 requested changes
Looks good :) Only small remarks

2023-09-14 10:24 UTC, niewim19 commented on ekf/logs/tests/tests.c
> +	};
State length may be subject to change. As its length is reasonably short (less than 30 I guess) it may be initialized with integers via loop. This way this test will stay ok.

2023-09-14 14:38 UTC, kemonats commented on ekf/logs/reader.c
> +	}
`logSize` is of type `size_t` and is never `< 0`

2023-09-18 09:14 UTC, PNieck commented on ekf/logs/reader.c
> +static int ekflog_readEnding(logType_t logType)
I have changed to `ekflog_postStore`

2023-09-19 09:01 UTC, merged

2023-09-19 10:13 UTC, kemonats commented on ekf/logs/reader.c
> +	}
You merged this PR, but continue to check if unsigned expression `logSize` is less than zero.

2023-09-19 13:01 UTC, PNieck commented on ekf/logs/reader.c
> +	}
No, I have changed type of return value of `ekflog_logSizeGet` to `int`

2023-09-20 09:17 UTC, PNieck commented on ekf/logs/reader.c
> +	}
Ok, yes - you were right. I have fixed this in separate PR https://github.com/phoenix-pilot/phoenix-pilot-core/pull/271