Ekf test runner
phoenix-pilot/phoenix-pilot-core pull request #270
Opened 2023-09-19 12:52 UTC by PNieck

## Description

PR adds ekf test runner. It allows to run EKF using prepared logs and compare final ekf status with expected one.

## Motivation and Context

Enable easy EKF functional tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `host-generic-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-09-27 09:21 UTC, niewim19 requested changes
Looks good, my biggest concerns are about naming so that it is descriptive, non repetitive and short.

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +static int ekftests_fieldToChange(const file_entry_t *entry, const char *fieldToChange)
Please add short comment what this function achieves

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +int ekftests_prepareConfigFile(char **fieldsToChange, int fieldsToChangeCnt)
```suggestion
int ekftests_prepareConfigFile(char **fields, int fieldsCnt)
```
phrase `fieldsToChange` is used extensively. Please add description to this function with argument description.

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.h
> + */
Please update description

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.h
> +int ekftests_prepareConfigFile(char **fieldsToChange, int fieldsToChangeCnt);
`ekftests_configPrepare()` sounds shorter yet still meaningful :) The same goes for `ekftests_configRestore`

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +static int ekftests_fileEntryGet(FILE *file, char **lineBuff, size_t *lineBuffLen, file_entry_t *entry)
suggestion: `ekftests_nextEntry`

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +}
Please move it to the end of the file

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/result_check.c
> +static int ekftests_statesAlloc(matrix_t *state1, matrix_t *state2, matrix_t *state3, matrix_t *state4)
It seems that four copies of state matrix are arbitrary. The cause for four copies is hidden in the upper layer. I think that each state purpose can be highlighted in its name:
```suggestion
static int ekftests_statesAlloc(matrix_t *expected, matrix_t *final, matrix_t *epsilon, matrix_t *diff)
```

2023-09-27 09:21 UTC, niewim19 commented on ekf/tests/test_runner/result_check.c
> +		;
This looks strange - please add description why it is done in such manner.

2023-09-28 08:53 UTC, niewim19 requested changes
Left remarks. Generally speaking:
 - good choice with `fieldsToChange` placement :)
 - `main.c` functions (beside `main`) lack `static` keyword. It is not necessary, but let`s stay with convention.

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> + * Author: Piotr Nieciecki
Please elaborate a little here (one/two sentences):

```suggestion
 * EKF test runner
 *
 * Executes ekf (...) via devekf (...) via copied `ekf.conf` file
 *
 * Copyright 2023 Phoenix Systems
 * Author: Piotr Nieciecki
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +	printf("\033[39m");
All other formatted/colored prints are one liners, this stands out
```suggestion
	printf("\033[34m\nChecking output\033[39m\n\n");
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +		return -1;
Return value differs from other error values:
```suggestion
		return EXIT_FAILURE;
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +int ekftests_testSetUp(char *scenarioFile)
not applied :) Also `static` may be used

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/result_check.c
> + * Part of EKF test runner
If we navigated here we know its part of EKF test runner :)
```suggestion
 * EKF test runner result checking routines
```
Please amend also the header file.

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> + * Part of EKF test runner
```suggestion
 * EKF test runner config preparation routines
```
Please amend header file accordingly.

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +	return -errno;
Value returned by this function is ambiguous as in case of error it may return `-1` which has no `errno` meaning by design (but is  _errnowise_ `EPERM`) or `errno` with some meaning. 

On the other hand no layer above checks for the return value meanign other than `!=0` so this `errno` return may be dropped in favor of `-1`.

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +	errno = 0;
Looks like unnecessary `errno` setting.

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.h
> + * These string should follow format <header>/<field name>=<value to use>
```suggestion
 * These string should follow format "<header>/<field_name>=<value_to_use>"
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +#define CHANGE
Looks like unused macro :)

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +	return 0;
```suggestion
	return ekftests_configPrepare(fieldsToChange, changes);
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +inline int ekftests_testTearDown(void)
I think `inline` may be dropped. Lets put this optimalization step on compiler if it wishes so. However:
```suggestion
static int ekftests_testTearDown(void)
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/main.c
> +void ekftests_usage(void)
```suggestion
static void ekftests_usage(void)
```

2023-09-28 08:53 UTC, niewim19 commented on ekf/tests/test_runner/result_check.c
> +	return err;
According to `parser_fieldGetFloat` description it returns _non-zero_ on error. Let's add proper check on return, as bitewise `or` summing may give strange results. It will definitely work, but it looks unsafe.
```suggestion
	return (err == 0) ? 0 : -1;
```

2023-09-28 08:53 UTC, niewim19 commented on utils/devekf.c
> +			}
`errno` is zeroed once, yet checked in loop without zeroing. There are other functions that can set errno to non-zero value which should not halt the program (e.g. `printf()`). I think that `res` approach may be dropped and `errno` check should be done explicitely on the function which error you`re wishing to catch.

2023-09-28 08:53 UTC, niewim19 commented on utils/devekf.c
> +	return res;
Please revert to use of `EXIT_SUCCESS`, as `EXIT_FAILURE` is used in other places.

2023-09-28 09:35 UTC, PNieck commented on ekf/tests/test_runner/main.c
> +	char *expectedResult;
I have changed `scenarioFile` to `scenarioName`, but `expectedResult` stayed. In my opinion `expectedName` can be misleading - it suggests that code under test returns some kind of name

2023-09-28 10:11 UTC, PNieck commented on ekf/tests/test_runner/config_file_handler.c
> +	errno = 0;
It's not unnecessary - i am using errno to distinguish between EOF and error in `ekftests_nextEntry`. I have added specific comments.

2023-09-29 08:59 UTC, niewim19 approved these changes

2023-09-29 08:59 UTC, niewim19 commented on ekf/tests/test_runner/config_file_handler.c
> +	errno = 0;
Ok, that makes sense. Sorry for remark.

2023-09-29 18:47 UTC, merged