GPS EKF comparison script
phoenix-pilot/phoenix-pilot-core pull request #280
Opened 2023-10-11 12:22 UTC by PNieck

## Description

Adds ekf log evaluation to for GPS and EKF status position comparison.

## Motivation and Context

Easier EKF verification

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `host-generic-pilot`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-10-12 09:19 UTC, niewim19 reviewed
Left some small hints. Everything seems clear enough that comments are not really needed. However, added lately README may need update with these evaluations added.

2023-10-12 09:19 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +def mikroseconds_to_seconds(microseconds):
```suggestion
def microseconds_to_seconds(microseconds):
```

2023-10-12 09:19 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +            dt = curr_log.timestamp - prev_log.timestamp
It may happen that two gps logs have the same timestamp. Better to skip extrapolation then.

2023-10-12 09:19 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +            gps_velocity_EW[i] = dist_e/dt
This may crash if two gps samples have the same timestamp (which is possible)

2023-10-18 08:38 UTC, niewim19 requested changes
- Handling `dt = 0` situation may be solved differently, for example, by using previous value, or assigning 0 by default.
 - Velocity and acceleration comparison lack legend.

2023-10-18 08:38 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +                continue
This may lead to out of bound index. `for` loop is bounded by `context.gps_logs` length which, at loops beginning, matches in sizes with `extrapolated_y`/`extrapolated_x`. But on the course of iteration `extrapolated_y` may be shortened, yet loop bounds stay the same. This manifests in line 208 and 209 where the values are assigned to `extrapolated_y`/`extrapolated_x` with `context.gps_logs` based index.

2023-10-18 08:38 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +            prev_to_curr_vec_y = curr_pos_y - prev_pos_y
```suggestion
            pos_dx = curr_pos_x - prev_pos_x
            pos_dy = curr_pos_y - prev_pos_y
```

2023-10-18 08:38 UTC, niewim19 commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +            curr_pos_y = self.calculate_gps_y(context.gps_logs[i])
If there is no `prev_vel_x` then it may be just:
```suggestion
            prev_x = self.calculate_gps_x(context.gps_logs[i-1])
            prev_y = self.calculate_gps_y(context.gps_logs[i-1])

            curr_x = self.calculate_gps_x(context.gps_logs[i])
            curr_y = self.calculate_gps_y(context.gps_logs[i])
```

2023-10-18 12:27 UTC, PNieck commented on scripts/ekf_logs/logs_evaluations/evaluations/gps_ekf_comparison.py
> +                continue
I have decided to use last value of `dt` in such cases

2023-10-19 07:45 UTC, niewim19 approved these changes

2023-10-19 07:47 UTC, merged