ekf: magnetic declination
phoenix-pilot/phoenix-pilot-core pull request #281
Opened 2023-10-13 13:00 UTC by niewim19

## Description

Adding earth magnetic field declination to ekf as apriori parameter.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: zturn drone

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-10-16 15:58 UTC, PNieck requested changes

2023-10-17 07:38 UTC, niewim19 commented on algebra/include/qdiff.h
> +int qvdiff_cqvqDiffQ(const quat_t *q, const vec_t *v, matrix_t *out);
Do you mean that `cjg` is used?

2023-10-18 08:52 UTC, PNieck commented on algebra/include/qdiff.h
> +int qvdiff_cqvqDiffQ(const quat_t *q, const vec_t *v, matrix_t *out);
As far as I can see - we do not annotate quaternion conjugation in naming convertion

2023-10-20 11:19 UTC, niewim19 commented on algebra/include/qdiff.h
> +int qvdiff_cqvqDiffQ(const quat_t *q, const vec_t *v, matrix_t *out);
As discussed, this will be corrected in separate PR as changes in multiple files are needed. 

https://github.com/phoenix-pilot/phoenix-pilot-core/issues/282

2023-10-23 11:55 UTC, PNieck requested changes

2023-10-25 09:12 UTC, PNieck submitted a review, later dismissed

2023-10-25 09:12 UTC, PNieck commented on ekf/kalman_implem.c
> +		return -1;
Not a stopper, but maybe some kind of error message is needed there

2023-10-25 10:31 UTC, PNieck approved these changes
LGTM

2023-10-25 10:31 UTC, merged