Activate ci
phoenix-pilot/phoenix-pilot-core pull request #291
Opened 2023-11-13 13:20 UTC by PNieck

## Description

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2023-11-14 10:31 UTC, damianloew commented on trunner_extension/host_pilot_runner_ext.py
> +class HostPilotTarget(HostPCGenericTarget):
Is it done to avoid executing basic host-generic-pc tests for Phoenix-RTOS within your's project?

2023-11-14 10:31 UTC, damianloew commented on trunner_extension/vpilot_runner_ext.py
> +from trunner.ctx import TestContext
Maybe it would be better to create another `tests` directory and then `trunner_extensions` within?

2023-11-14 10:31 UTC, damianloew commented on algebra/tests/README.md
> +- `test.yml` - specifies test case for our test runner
About the commit message:
`CI: add yaml file for Phoenix test runner` -> `CI: add yaml files for Phoenix test runner`

2023-11-14 10:31 UTC, damianloew commented on ekf/logs/tests/test.yml
> +        value: [host-generic-pilot]
I'd remove this commit and just don't add not supported target at once, but @niewim19 decision is yours :smiley:

2023-11-14 10:36 UTC, damianloew requested changes
Overall it looks really clean, I am happy that it could have been done in a convenient way. Only small remarks left.

2023-11-14 10:41 UTC, damianloew commented on ekf/logs/tests/test.yml
> +      execute: ../usr/bin/ekflog_tests
To avoid this please wait for https://github.com/phoenix-rtos/phoenix-rtos-tests/pull/290 merge and pass there `/usr/bin/ekflog_tests`. Applies to the other places.

2023-11-15 10:46 UTC, PNieck commented on trunner_extension/vpilot_runner_ext.py
> +from trunner.ctx import TestContext
Decision is yours @niewim19

2023-11-15 11:02 UTC, niewim19 commented on trunner_extension/vpilot_runner_ext.py
> +from trunner.ctx import TestContext
It will not clutter the main directory. I agree with @damianloew, lets go for it

2023-11-15 11:42 UTC, PNieck commented on ekf/logs/tests/test.yml
> +      execute: ../usr/bin/ekflog_tests
This change works with host targets? If there will be `/usr/bin/ekflog_tests`, then it knows, that it is a path relative to `_fs/<project>/root`?

2023-11-15 11:49 UTC, PNieck commented on trunner_extension/vpilot_runner_ext.py
> +from trunner.ctx import TestContext
Done

2023-11-15 12:47 UTC, damianloew commented on ekf/logs/tests/test.yml
> +      execute: ../usr/bin/ekflog_tests
Good note, we will also add it within the mentioned PR.

2023-11-17 11:55 UTC, niewim19 submitted a review, later dismissed

2023-11-17 12:02 UTC, niewim19 approved these changes

2023-11-17 12:33 UTC, damianloew approved these changes
Thanks for the improvements! LGTM

2023-11-17 12:40 UTC, merged