quad-control: accounting for angles boundary values in pid calculations
phoenix-pilot/phoenix-pilot-core pull request #32
Opened 2022-07-28 10:20 UTC by niewim19

## Description

Currently no boundary values check is performed on values that go to pid. Proposed solution:
 - adds boundary values specification in ekflib
 - adds reading those ekflib bounds in quad-control:control.c
 - accounts for boundary values in pid calculation process

Symmetric boundary values are assumed.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: zturn drone

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [x] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-07-29 11:12 UTC, HBuczynski requested changes
You don't need additional structure `quad_bounds_t.` `quad_common` keeps information about pids. You have already added `boundVal` to `pid_ctx_t`. Please use this field in `pid` unit. Then, no additional arguments have to be passed to `pid_calc`.

2022-07-29 11:12 UTC, HBuczynski commented on quadcontrol/control.c
> +	ekf_boundsGet(&(quad_common.bounds.boundYaw), &(quad_common.bounds.boundRoll), &(quad_common.bounds.boundPitch));
You don't need brackets.

2022-08-02 10:32 UTC, niewim19 commented
Moved boundary values logic to `pid` module all together

2022-08-02 10:41 UTC, HBuczynski commented on quadcontrol/pid.c
> +	pid->boundVal = NO_BOUNDVAL;
`pid->boundVal` should not be changes within `pid_calc` function

2022-08-02 10:41 UTC, HBuczynski commented on quadcontrol/pid.c
> +
You don't check the case for `NO_BOUNDVAL`.

2022-08-02 10:41 UTC, HBuczynski commented on quadcontrol/pid.h
> +	float boundVal; /* positive boundary value for process variable (symmetric boundary value assumed) */
If it is only associated with error, the name should be more precise.

2022-08-02 10:55 UTC, niewim19 commented on quadcontrol/pid.c
> +	pid->boundVal = NO_BOUNDVAL;
And it's not. Referenced line is in `pid_init(pid_ctx_t *pid)`

2022-08-02 10:55 UTC, niewim19 commented on quadcontrol/pid.c
> +
It does not need to be checked. That`s why NO_BOUNDVAL is equal to `0.0`. It does not change the outcome.

However I added `if` for that. Just for clarity and some floating point operation saving.

2022-08-02 10:56 UTC, niewim19 commented on quadcontrol/pid.h
> +	float boundVal; /* positive boundary value for process variable (symmetric boundary value assumed) */
Changed to include 'err' prefix. Thanks!

2022-08-02 11:00 UTC, HBuczynski commented on quadcontrol/pid.c
> +	pid->boundVal = NO_BOUNDVAL;
Sorry, my mistake.

2022-08-02 11:28 UTC, HBuczynski approved these changes

2022-08-02 11:32 UTC, merged