tools/mctl: add motor control library libmctl
phoenix-pilot/phoenix-pilot-core pull request #39
Opened 2022-08-05 07:14 UTC by niewim19

JIRA: PP-89

## Description

Adding general motor control library `libmctl` with:
 - engines init/deinit functions
 - engines arming/disarming functions with safety control
 - engines throttle control

## Motivation and Context

More applications are goint to use engines, so good engines control module is needed. This PR share `tools/` structure with:
 - https://github.com/phoenix-pilot/phoenix-pilot-core/pull/38

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-08-05 07:22 UTC, niewim19 commented on tools/mctl/mctl.h
> +enum thrtlTempo {tempoInst, tempoSlow, tempoHigh};
Leaving unresolved, this will not be corrected in any way.

2022-08-24 11:14 UTC, niewim19 commented on tools/mctl/mctl.h
> +enum thrtlTempo { tempoInst, tempoSlow, tempoHigh };
Remark not valid

2022-08-24 11:21 UTC, niewim19 commented
Current CI remarks not valid (enum formatting issue)

2022-08-30 08:57 UTC, niewim19 commented on libs/mctl/mctl.h
> +enum thrtlTempo { tempoInst, tempoSlow, tempoHigh };
unresolvable

2022-08-30 13:26 UTC, HBuczynski requested changes

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	unsigned int mots;          /* number of motors */
```suggestion
	FILE **pwmFiles;           /* motors pwm files descriptors */
	float *mThrottles;              /* motors current throttle value */
	unsigned int init;  /* motors descriptors initialization flag */
	unsigned int armed; /* motors armed/disarmed flag */
	unsigned int mNb;          /* number of motors */
```

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> + * mctl.h - motors control module
upss, copy-paste

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	if (motorIdx >= mctl_common.mots) {
```suggestion
static int mctl_motWrite(unsigned int id, float thrtl)
{
	unsigned int pwmVal;

	if (id >= mctl_common.mNb) {
```

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	return (motorIdx >= mctl_common.mots || fprintf(mctl_common.motorFile[motorIdx], "0") < sizeof("0") - 1) ? -1 : 0;
Too hackish way.
The code is not readable.

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	if (!mctl_common.mctlInitFlag || !mctl_common.mctlArmedFlag) {
To be compliant with MISRA rules:
```suggestion
	if (mctl_common.mctlInitFlag == 0 || mctl_common.mctlArmedFlag == 0) {
```

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	}
Shouldn't the function return with the error?

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +				break;
These values are known in compile time. You can put them in a table and, `tempoSlow` & `tempoHigh` can be indexes in the table.

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +		currThrtl = mctl_common.mThrtl[motorIdx];
Potential buffer overflow. The `motorIdx` is not checked.

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +			printf("Failed at opening %u-th motor descriptor\n", i);
Be consistent with the rest of the code:
`fprintf(stderr,`

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	if (!err) {
MISRA

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +		} while (flag && rep > 0);
`rep > 0` - it is always true

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.c
> +		if (mctl_motWrite(i, THROTTLE_DOWN)) {
MISRA

2022-08-30 13:26 UTC, HBuczynski commented on libs/mctl/mctl.h
> +void mctl_deinit(void);
Add two spaces between functions.

2022-08-31 08:51 UTC, niewim19 commented on libs/mctl/mctl.c
> +				break;
Thanks for that idea!

2022-08-31 08:51 UTC, niewim19 commented on libs/mctl/mctl.c
> +	}
Oh. Yes it should. My mistake.

2022-08-31 08:51 UTC, niewim19 commented on libs/mctl/mctl.c
> +	if (!mctl_common.mctlInitFlag || !mctl_common.mctlArmedFlag) {
As these are strict boolean flags `bool` type was used

2022-08-31 08:58 UTC, niewim19 commented
Crucial changes after review:
 - names of some variables changed
 - used strictly `fprintf`
 - `init` and `armed` flag are now declared as `bool`
 - throttle change rate logic changed with a use of array of predefined values
 - minor editorial fixes (mostly spacing)

2022-08-31 09:16 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	}
Please add empty lines between two `if` and `return`.

2022-08-31 09:16 UTC, HBuczynski commented on libs/mctl/mctl.c
> +	if (fprintf(mctl_common.pwmFiles[id], "0") < (sizeof("0") - 1)) {
```suggestion
	if (fprintf(mctl_common.pwmFiles[id], "0") < 0) {
```

2022-08-31 09:29 UTC, niewim19 commented on libs/mctl/mctl.c
> +	if (fprintf(mctl_common.pwmFiles[id], "0") < (sizeof("0") - 1)) {
So if due to some error we succesfully write zero bytes to the stream we would treat it as success of `mctl_motOff` which might be dangerous, as it would not shut down motors.

2022-08-31 10:10 UTC, niewim19 commented
Changed `fprintf()` success checks

2022-08-31 10:21 UTC, HBuczynski approved these changes

2022-08-31 10:24 UTC, merged