algebra: adding tests for `matrix_at()` function in `matrix` library
phoenix-pilot/phoenix-pilot-core pull request #42
Opened 2022-08-05 14:32 UTC by PNieck

JIRA: PP-71

## Description

This PR is adding tests for function `matrix_at`

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).  `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-08-05 17:39 UTC, niewim19 requested changes
This function will be later used to do _blackbox_ testing of other `matrix` functions. But here we want to ensure that what we read is actually from our matrix, and from given position in the array.  We need _whitebox_ testing here. When correct write/read is asserted we can go on and just use `matrix_at()` as the only proper way of reading elements from array for tests. That's why I encourage (probably only here) to use _by hand_ changes in memory pointed by `data`. 

Note: let's keep test name notation as: `matrix_<funcName>_typeOfTest`, for example: `matrix_product_sizeMismatch`

2022-08-05 17:39 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_at, matrix_at_writing_and_reading)
I would do two tests - the one with writing, and the one with reading. You can manipulate memory `matrix_t->data` _by hand_ so that is of expected form.

2022-08-05 17:39 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	col = (COLS - 3 < 0) ? 0 : COLS - 3;
magic numbers here. You can specify (with comment by `#define`) that `COLS` or `ROWS` should be bigger than e.g 2. Then, you can drop conditional and just use `COLS / 2` to ensure that you are inside the matrix column-wise, or:
 - `COLS + 1` to ensure that you are just outside the matrix column-wise (strange edge cases? Off-by-one?)
 - `COLS * ROWS * 2` to ensure that you are for sure outside the whole matrix memory scope.

The same applies for `ROWS`. This way you can drop the `row` and `col` variables and hardcode those values inside `matrix_at()` usage.

2022-08-16 10:47 UTC, PNieck commented on algebra/tests/matrix/various.c
> +	col = (COLS - 3 < 0) ? 0 : COLS - 3;
I leave `row` and `col` as it is - to not repeat the code

2022-08-18 12:25 UTC, damianloew submitted a review, later dismissed
I think that applied changes are sufficient and this simple test could be merged.

2022-08-22 09:17 UTC, PNieck commented
I have moved this tests to new file and added README, which describes which function where is tested - for better clarity.

2022-08-22 10:08 UTC, niewim19 submitted a review, later dismissed
Final touches and it will be good to go :)

2022-08-22 10:08 UTC, niewim19 commented on algebra/tests/matrix/basic_interactions.c
> +	}
```suggestion
	i = 0;
	for (row = 0; row < ROWS; row++) {
		for (col = 0; col < COLS; col++) {
			matElem = matrix_at(&stMat, row, col);
			TEST_ASSERT_NOT_NULL(matElem);
			
			/* Assigning different value to every matrix element and logically corresponding position in exp_data */
			*matElem = exp_data[row * COLS + col] = i;
			i++;
		}
	}
```

2022-08-22 10:18 UTC, PNieck commented on algebra/tests/matrix/basic_interactions.c
> +	int bigShift = 1234;
I agree

2022-08-22 10:25 UTC, niewim19 approved these changes
LGTM

2022-08-22 10:28 UTC, merged