ekf: application to library conversion of EKF filter
phoenix-pilot/phoenix-pilot-core pull request #5
Opened 2022-06-21 11:12 UTC by niewim19

2022-06-22 13:15 UTC, MaciejPurski commented on ekf/kalman_implem.h
> +	float dt;            /* current time step length */
As above.

2022-06-22 13:26 UTC, MaciejPurski commented on ekf/sensors_client.c
> +				*baro_evt = data->events[j];
Check my `sensGps` comment.

2022-06-22 13:26 UTC, MaciejPurski commented on ekf/sensors_client.c
> +				*accel_evt = data->events[j];
Check my `sensGps` comment.

2022-06-22 13:27 UTC, MaciejPurski commented on ekf/sensors_client.c
> +				// printf("acce - x: %u, y: %u, z: %u\n", data->events[j].accels.accelX, data->events[j].accels.accelY, data->events[j].accels.accelZ);
Maybe disable those lines using some define or define a debug macro?
```suggestion
#if EKF_DEBUG
				printf("Accel, timestamp: %llu\n", data->events[j].timestamp);
				printf("acce - x: %u, y: %u, z: %u\n", data->events[j].accels.accelX, data->events[j].accels.accelY, data->events[j].accels.accelZ);
#endif
```

2022-06-22 13:27 UTC, HBuczynski requested changes
I have not made a detail review, just points out several significant things:
- there is a mix of convention; please take care of using only camelCase,
- avoid using global variables, especially in macros in header files,
- each file should begin with description,
- functions should be written in the following manner: `module_functionality`

2022-06-22 13:27 UTC, HBuczynski commented on ekf/kalman_core.h
> +	(measurementEngine.Z) = &ekf_Z; \
You are making a reference in this macro to many global variables. It is not a good practice to have so many global variables. It has to be refactored in a future.

2022-06-22 13:27 UTC, HBuczynski commented on ekf/measurement.c
>  	//float xEcef, yEcef, zEcef;
If it is not used, please remove it.

2022-06-22 13:28 UTC, MaciejPurski commented on ekf/sensors_client.c
> +	client_gps };
The previous version was more compliant with our style.
```suggestion
enum sensor_fd { client_imu, client_baro, client_termo, client_gps };
```

2022-06-22 13:29 UTC, MaciejPurski commented on ekf/sensors_client.c
> +	int fd[4]; /* each for one sensor type */
Maybe better use a define for a number of sensor types instead of a comment.

2022-06-22 14:47 UTC, niewim19 commented on ekf/kalman_core.h
> +#include "tools/phmatrix.h"
`include` moved before first define, as discussed

2022-06-22 14:54 UTC, niewim19 commented on ekf/kalman_implem.c
> +	.P_aerr = 0.01F,           /* 0.001 m/s^2 */
Thank you, I will keep an eye on those `f`s. I think here these `f`s are unnecessary, dropped `f`s all together for better readibility in `init_values` presets.

2022-06-22 14:56 UTC, niewim19 commented on ekf/measurement.c
> +extern void sensGps(sensor_event_t *gps_evt);
added sensclient_ prefix for those funtions, moved them to separate header

2022-06-22 15:17 UTC, niewim19 commented on ekf/ekflib.c
> +	kalman_common.run = 1;
used gnu builtins `__atomic_add_fetch` and `__atomic_sub_fetch`

2022-06-22 15:18 UTC, niewim19 commented on ekf/kalman_implem.h
> +	float t;             /* total time since filtering begin */
total simulation time variable removed

2022-06-22 16:10 UTC, niewim19 commented on ekf/kalman_implem.h
> +	float t;             /* total time since filtering begin */
moved to time_t for as long as possible to store time values

2022-06-22 16:10 UTC, niewim19 commented on ekf/kalman_implem.h
> +	float dt;            /* current time step length */
moved to time_t to store time values for as long as possible

2022-06-23 07:45 UTC, niewim19 commented on ekf/ekflib.c
> +	while (kalman_common.run == 1) {
taken care of it, it is now:
 - set to 0 in `ekf_init`
 - set to 1 by `__atomic_store_n` in `ekf_thread`
 - set to 0 `__atomic_store_n` in `ekf_done`

2022-06-23 07:58 UTC, niewim19 commented on ekf/sensors_client.c
> +				*gps_evt = data->events[j];
There is assumption that such event will occur only once in the list. Moreover, the goal is to retrieve all three types of events: `SENSOR_TYPE_ACCEL`, `SENSOR_TYPE_MAG` and `SENSOR_TYPE_GYRO` (each of which shall occur once). 

With those assumptions and goals this solution seems optimal. If there were more events of such type (strange returns from sensorhub?) this solution is indeed not optimal (but sufficient).

2022-06-23 08:08 UTC, niewim19 commented on ekf/sensors_client.c
> +	client_gps };
but i am not sure if clang-format will not complain :P

2022-06-23 10:36 UTC, HBuczynski approved these changes
The code needs some cleaning up, but taking into account project time frames we should merge it ASAP.

2022-06-23 10:37 UTC, merged