Neiwim19/mma2mctl
phoenix-pilot/phoenix-pilot-core pull request #64
Opened 2022-08-29 06:26 UTC by niewim19

## Description

Using `libmctl` rewrite procedures in quadcontrol:mma module.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: zturn drone

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [x] This PR needs additional PRs to work:
  - https://github.com/phoenix-pilot/phoenix-pilot-core/pull/38
  - https://github.com/phoenix-pilot/phoenix-pilot-core/pull/39
- [ ] I will merge this PR by myself when appropriate.

2022-08-29 06:27 UTC, niewim19 commented on tools/mctl/mctl.h
> +enum thrtlTempo { tempoInst, tempoSlow, tempoHigh };
Invalid remark: won`t be corrected

2022-08-30 11:31 UTC, niewim19 commented on libs/mctl/mctl.h
> +enum thrtlTempo { tempoInst, tempoSlow, tempoHigh };
Unresolvable

2022-08-31 13:48 UTC, HBuczynski requested changes

2022-08-31 13:48 UTC, HBuczynski commented on quadcontrol/mma.c
>  	unsigned int armed;
Is it still used?

2022-08-31 13:48 UTC, HBuczynski commented on quadcontrol/mma.c
> +const char *motorPaths[] = {
```suggestion
static const char *motorPaths[] = {
```

2022-08-31 13:48 UTC, HBuczynski commented on quadcontrol/mma.c
>  	if ((err = mutexCreate(&mma_common.lock)) < 0) {
I know that it is not a part of Your PR, but I think it can be fixed to be consistent with MISRA:
```suggestion
        err = mutexCreate(&mma_common.lock)
	if ((err < 0) {
```

2022-08-31 13:48 UTC, HBuczynski commented on quadcontrol/mma.c
>  #define PWM_MIN_SCALER 100000
To removed.

2022-08-31 13:57 UTC, niewim19 commented on quadcontrol/mma.c
>  	if ((err = mutexCreate(&mma_common.lock)) < 0) {
Good idea! Applied.

2022-08-31 13:58 UTC, niewim19 commented
Applied all remarks from review. Commits to be squashed into one at merge time.

2022-08-31 13:59 UTC, HBuczynski approved these changes

2022-08-31 14:01 UTC, merged