P nieck/refactoring matrix library
phoenix-pilot/phoenix-pilot-core pull request #70
Opened 2022-08-30 13:24 UTC by PNieck

JIRA: PP-71

## Description

Fixing behavior of some function from `matrix` library

## Motivation and Context

We want to have safer functions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-09-02 09:30 UTC, niewim19 requested changes
Some stylistic remarks, and some major ones:
 - returning in some functions leave invalid data in outcome matrix, or temporary buffer

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +		if ((C->rows != A->rows || C->cols != A->cols) && (C->rows != A->cols && C->cols != A->rows)) {
```suggestion
		if (!(C->rows == A->rows && C->cols == A->cols) || !(C->rows == A->cols && C->cols == A->rows)) {
```
Just a suggestion. You can leave it as it is, this feels more natural as we check if they: (don't have common sizes) or (don't have common sizes if some is transposed)

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +		if ((C->rows != A->rows || C->cols != A->cols) && (C->rows != A->cols && C->cols != A->rows)) {
The same remark about logic operations transformation. Do as you wish :)

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
Remark about _algebra: fixing `matrix_cmp` function_ commit message: function returns -1, not false :)
Also, if you refactor this code - consider making this functions parameters as const.

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +			if (A->rows != B->cols || C->cols != B->rows || C->rows != A->cols) {
The same remark about logic: do as you wish

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +			if (A->cols != B->cols || A->rows != B->rows) {
Not in scope of this PR, but please add comments as in `matrix_prod()`:
```suggestion
			/* both transposed */
			if (A->cols != B->cols || A->rows != B->rows) {
```

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +			return -1;
The returning must be redesigned. If we return here, no calculations was performed on `C` data, but `C` matrix metadata (rows/cols/transposed) was copied from `A`, so we change it but only slightly.

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +			return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +			return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +				return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +				return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +				return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
> +				return -1;
Returning here leaves C partially modified

2022-09-02 09:30 UTC, niewim19 commented on algebra/matrix.c
>  {
Consider checking data integrity here. Otherwise, if first `matrix_prod()` succeeds and second failed we have changed `tempC`. This **is** a temporary buffer, but we should not just paste garbage there.

There are strict rules over colspan/rowspan of each matrix. You can use fresh `matrix_colsGet`/`matrix_rowsGet` to not deal with transpositions as this function is just a multiplication wrapper.

2022-09-02 12:08 UTC, PNieck commented on algebra/matrix.c
> +		if ((C->rows != A->rows || C->cols != A->cols) && (C->rows != A->cols && C->cols != A->rows)) {
Ok, but in your suggestion the middle operator should be `&&`

2022-09-05 15:04 UTC, niewim19 requested changes
Only small changes to the code are needed. Mainly editorial.

2022-09-06 13:10 UTC, niewim19 approved these changes
LGTM

2022-09-06 13:10 UTC, niewim19 commented on algebra/matrix.c
> +			if (A->cols != B->cols || A->rows != B->rows) {
Still no comments :)

2022-09-06 14:35 UTC, merged