Adding tests for `matrix prod`
phoenix-pilot/phoenix-pilot-core pull request #71
Opened 2022-08-31 12:46 UTC by PNieck

PP-71

## Description

This PR adds tests for `matrix_prod` function.

## Motivation and Context

More precise tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here).  `armv7a9-zynq7000-qemu`
 
## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-08-31 14:34 UTC, niewim19 requested changes
Doing partial review as a lot may change after suugested changes

2022-08-31 14:34 UTC, niewim19 commented on algebra/tests/matrix/tools_tests.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_realTrp(&M1));
this will not be needed when `realTrp` changes approach

2022-08-31 14:34 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +}
These functions look like they could be written straight into `TEST_TEAR_DOWN` and `TEST_SETUP` to not obscure operations from the reader/user

2022-08-31 14:34 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +int algebraTest_identicalMatrix(matrix_t *M1, matrix_t *M2)
Shouldn't it be checked correctly by `matrix_cmp`? Would it be possible to test `matrix_cmp` first and then just use it?

2022-08-31 14:51 UTC, PNieck commented on algebra/tests/matrix/tools.c
> +	}
It is possible with square matrices, but not with others

2022-09-01 09:11 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	}
Yes, you are right. As discussed it is a borad topic known as "matrix in-place transposition". Current approach is both fast and simple to understand. Please add respective comment so no one reading that code in the future will have to dig into that topic again :) Maybe just a wikipedia link https://en.wikipedia.org/wiki/In-place_matrix_transposition

2022-09-01 09:12 UTC, niewim19 commented on algebra/tests/matrix/tools_tests.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_realTrp(&M1));
To be ignored after previous discussion

2022-09-01 11:55 UTC, PNieck commented on algebra/tests/matrix/tools.c
> +int algebraTests_trpCheck(matrix_t *M1, matrix_t *M2)
But this is not a test - this is function which checks if M1 is equal to transposed M2

2022-09-02 07:44 UTC, niewim19 requested changes
As I checked commit by commit, there are some remarks that I saw being repaired in further commits. 

My biggest remarks are about double transposition and spacing in `matrix_prod()` tests:
 - please move, if it is not already in good place, `M3` allocation before double transposition into the preparation step. I made comments about it, but to not pollute the review I am describing it here as it affects almost all tests
 - I would suggest to make a function that double transposes the matrix pointed with a pointer. It might be then properly described once, and not each time it is performed. And it needs that description as for a new reader it might be surprising why we transpose it two times and do the product as before and call it a separate test :)

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	}
```suggestion
	unsigned int row, col, nRows, nCols;

	nRows = matrix_rowsGet(M1);
	nCols = matrix_colsGet(M1);

	if (nRows != matrix_colsGet(M2) || nCols != matrix_rowsGet(M2)) {
		return CHECK_FAIL;
	}
```

After the check you do not need `M2` colspan and rowspan. Not a blocker, but removing redundancies.

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools_tests.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_realTrp(&M1));
I think this might be more readable, as you clearly separate the `matrix_trp` and `realtrp` from each other:

``` suggestion
	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M2, &M1));

	matrix_trp(&M1);
	matrix_trp(&M2);

	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_realTrp(&M1));
```
edit: valid as long as `algebraTests_matrixCopy` copies also transposition flag (I guess it does :) )

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools_tests.c
> +
Same as in previous one
```suggestion
	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M2, &M1));
	
	matrix_trp(&M1);
	matrix_trp(&M2);
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/buffs.h
> +
Please, add a short comment here describing the strange form of _in-declaration_ divisions.

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	for(i=0; i < M1->rows * M1->cols; i++) {
``` suggestion
	for(i = 0; i < M1->rows * M1->cols; i++) {
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	int i;
``` suggestion
	unsigned int i;
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools.h
> +/* Checks if M1 is identical to M2 */
Add short mention about its difference to `matrix_cmp()` to preserve a `float` errors information

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +		algebraTests_createAndFill(&Exp, buffs_rowsCtimesD, buffs_colsCtimesD, buffs_CtimesD, buffs_colsCtimesD * buffs_rowsCtimesD));
There is no need to allocate memory for Exp. You can just localy declare that matrix as const
```suggestion
const matrix_t Exp = { data = buffs_CtimesD, .rows = buffs_rowsCtimesD, .cols = buffs_colsCtimesD, .transposed = 0 };
```
If this is suitable then it applies in more tests in that file.

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +int algebraTest_identicalMatrix(matrix_t *M1, matrix_t *M2)
Ok, thats right. But I found this to be suitable :)
```suggestion
int algebraTest_identicalMatrix(const matrix_t *M1, const matrix_t *M2)
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +
No space here please. This is the preparation part of test and should be grouped together.

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Matrix transposed two times, so it is the same, but .transposed is true */
```suggestion
/* Double transpose with different functions. Mathematically the same, but structurally different */
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Matrix transposed two times, so it is the same, but .transposed is true */
```suggestion
/* Double transpose with different functions. Mathematically the same, but structurally different */
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Matrices transposed two times, so it is the same, but .transposed is true */
```suggestion
/* Double transpose with different functions. Mathematically the same, but structurally different */
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, matrix_bufAlloc(&M3, Exp.rows, Exp.cols));
Move `M3` allocation before transpositions of `M2` into the preparation part

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, matrix_bufAlloc(&M3, Exp.rows, Exp.cols));
Move `M3` allocation before `M1` transposition into the preparation part

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, matrix_bufAlloc(&M3, Exp.rows, Exp.cols));
Move `M3` allocation into the preparation step, before transpositions

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +
Remove space, this is still preparation part

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Matrix transposed two times, so it is the same, but .transposed is true */
```suggestion
/* Double transpose with different functions. Mathematically the same, but structurally different */
```

2022-09-02 07:44 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +
Remove space

2022-09-02 08:38 UTC, PNieck commented on algebra/tests/matrix/tools.c
> +int algebraTests_trpCheck(matrix_t *M1, matrix_t *M2)
Ok, that is a good idea

2022-09-02 09:02 UTC, PNieck commented on algebra/tests/matrix/tools.c
> +	buf = malloc(sizeof(float) * M->rows * M->cols);
LGTM

2022-09-02 11:15 UTC, PNieck commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Matrix transposed two times, so it is the same, but .transposed is true */
I have made special function, so comment is outdated

2022-09-02 14:09 UTC, niewim19 requested changes
Overall idea for `matrix_prod()` tests:
 - create two test groups, one for standard matrices and one for big matrices.
 - use about 6 static matrices with static buffers of correct size
 - at TEST_SETUP copy contents of correct buffer (for correct group) from `buffs.h` and set correct sizes of matrices
 - at TEST_TEAR_DOWN probably nothing will have to be done 


This way we can omit recreating the same matrix dynamically each time as it pollutes the test code

2022-09-05 10:48 UTC, niewim19 requested changes
Small remarks left. Let`s merge it soon :)

2022-09-05 10:48 UTC, niewim19 commented on algebra/tests/matrix/tools.h
> +/* Transposes matrix by rearranging its elements. Does not change M->transposed */
```suggestion
Transposes matrix by rearranging its elements. M must be allocated with matrix_bufAlloc(). Does not change M->transposed
```

Or even better - copy the temporary matrix data to `M` data after rearranging, so that it would be safe for matrices with static data buffer.

2022-09-05 10:48 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +	/* Getting matrix C */
The `algebraTests_createAndFill` is just fancy assignment operator, as you are dealing with memory buffers :)
``` suggestion
	/* Set M1 = C */
```
This quickly gives idea what is happening here. Applies in multiple places.

2022-09-05 10:48 UTC, niewim19 commented on algebra/tests/matrix/tools.h
> +extern int algebraTests_trpFlagChange(matrix_t *M);
`algebraTests_trpFlagChange` suggests that only flag is changed, which happens to be the same as plain `matrix_trp`. Maybe 
``` suggestion
extern int algebraTests_multiTrp(matrix_t *M);
```
or 
``` suggestion
extern int algebraTests_swapTranspose(matrix_t *M);
```

2022-09-05 10:48 UTC, niewim19 commented on algebra/tests/matrix/tools.h
> +/* Negates .transposed flag and rearranges matrix elements, so it is the same as it was */
``` suggestion
/* Transpose `M` using matrix_trp() and swap its memory so it is also transposed. Does not change `M` in mathematical meaning */
```

2022-09-05 10:48 UTC, niewim19 commented on algebra/tests/matrix/matrix_multiplication.c
> +/* FIXME: Add tests for incorrect matrix sizes to multiply */
You can write such testcase, put it in the end and ignore it :) For now just move this comment into TEST_GROUP_RUNNER after all tests so it does not just _hang_ here

2022-09-05 11:09 UTC, PNieck commented on algebra/tests/matrix/tools.h
> +/* Transposes matrix by rearranging its elements. Does not change M->transposed */
I have chosen second option - with copying buffor

2022-09-05 11:20 UTC, PNieck commented on algebra/tests/matrix/tools.h
> +extern int algebraTests_trpFlagChange(matrix_t *M);
Second option is better in my opinion. But i have changed this to `algebraTests_transposeSwap` - more consistent with our naming conventions

2022-09-05 11:27 UTC, niewim19 approved these changes
LGTM

2022-09-05 11:31 UTC, merged