calib: calibration tool framework
phoenix-pilot/phoenix-pilot-core pull request #73
Opened 2022-09-01 08:06 UTC by niewim19

- used linked list for procedures registration
 - calibration file read/write procedures undeclared

JIRA: PP-89

## Description

Drone calibration tool framework. Each calibration procedure registers itself via constructor using static structure from its source file.

## Motivation and Context

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [ ] I will merge this PR by myself when appropriate.

2022-09-01 09:37 UTC, HBuczynski requested changes

2022-09-01 09:37 UTC, HBuczynski commented on calib/mag.c
> +int cal_magmot_write(FILE *file)
General remark: 
- please use camelCase, 
- add `static` keyword to functions which scope is in a source file.

2022-09-01 09:37 UTC, HBuczynski commented on calib/mag.c
> +	return magHelp;
```suggestion
	return "Magnetometer vs engine interference calibration\n";
```

2022-09-01 09:37 UTC, HBuczynski commented on calib/main.c
> +		fprintf(stderr, "calibtool: Use option '-h' to print help.\n");
You can print the help.

2022-09-01 09:37 UTC, HBuczynski commented on calib/main.c
> +	if (cal == NULL) {
End of the list is always `NULL`. This condition does not make sense.

2022-09-01 09:37 UTC, HBuczynski commented on calib/main.c
> +	}
```suggestion
	if (ret < 0) {
	    error msg;
	    return EXIT_FAILURE;
	}
	
	ret = calib_writeAll();
	if (ret < 0)
	    TBD
```

2022-09-01 14:22 UTC, niewim19 commented
This PR was heavily remodeled to use simple hash map implementation, thus probably need another, full review.

2022-09-09 07:39 UTC, HBuczynski requested changes

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.h
> +	size_t used;        /* used capacity of hashmap */
The common way to name these fields for containers (e.x. C++ stl):
```suggestion
	size_t capacity;      /* maximum capacity of hashmap */
	size_t size;        /* used capacity of hashmap */
```

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.h
> +} hmap;
```suggestion
} hmap_t;
```

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +	hmap_entry_t *entries;
I don't think that this temporary variable is needed. You can use a field from `hm`.

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +	hash = i = hmap_hash(key) % hm->nitems;
Not readable.

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +	} while (i != hash);
I would suggest to split it into two cases, not gathering everything in the `do {...} while` loop. 
The first one check whether there is an empty bucket in the hash map, add the element and return.
The second case is handled in case of collision and the You have to update the list for specific bucket.

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +int hmap_insert(hmap *hm, const char *key, void *val)
Please check the input arguments.

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +	} while (i != hash);
The same comment as in the `hmap_insert` function.

2022-09-09 07:39 UTC, HBuczynski commented on calib/hmap.c
> +void *hmap_next(hmap *hm, unsigned int *iter)
General comment to all functions. Please verify whether input arguments are not `NULL` pointers.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magiron.c
> +	return "  Magnetometer calibration against soft/hard iron interference.\n";
What is the reason of the initial indent? I think that indents should be done in a higher layer.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magiron.c
> +static int cal_magironInterpret(const char *valName, float val)
General comment:
What is the reason to add a prefix `val` to variables? I think that `name` would be enough.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magiron.c
> +	magiron_common.softCal.rows = 3;
If some magic numbers are repeated, try to replace the by `define`.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magiron.c
> +	*matrix_at(&magiron_common.softCal, 2, 2) = 1.0593312;
Some nitpicking. I would suggest to put this code into separate function.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magmot.c
> +#define AVG_WAIT     1000 * 10
```suggestion
#define AVG_WAIT     (1000 * 10)
```

2022-09-09 07:39 UTC, HBuczynski commented on calib/magmot.c
> +*/
I really appreciate comments.

2022-09-09 07:39 UTC, HBuczynski commented on calib/magmot.c
> +	return "  Magnetometer vs engine interference calibration\n";
The some comment as in the `magiron`

2022-09-09 07:39 UTC, HBuczynski commented on calib/main.c
> +}
Wraper for a function? I would suggest to use explicitly `hmap_get`.

2022-09-09 07:39 UTC, HBuczynski commented on calib/main.c
> +			if (cal->interpret(head, atof(val)) != EOK) {
Check whether `interpret` is not a `NULL`

2022-09-09 07:39 UTC, HBuczynski commented on calib/main.c
> +	ret = cal->init(argc, argv);
Please verify whether all callback are not set to `NULL`.

2022-09-09 09:44 UTC, niewim19 commented on calib/hmap.c
> +	} while (i != hash);
I slightly refactored the code here, but as this functions have to check for more parameters it is still cleaner to enter `while` loop at least once. Changed it to be normal while, not `do...while` with fast NULL check in the beginning.

2022-09-09 10:17 UTC, niewim19 commented on calib/calib.h
> +	struct _calib_t *next; /* linked list pointer */
Removed

2022-09-09 10:23 UTC, niewim19 commented
Changes after review were implemented as separate commits in this branch history as follows:

- Changes to `main.c`, `hmap.h`, `hmap.c` and `calib.h` were done in: https://github.com/phoenix-pilot/phoenix-pilot-core/pull/73/commits/0df06c2448496677c8fb057c6d0ca47ee7eda82f
- Changes to `magmot` calibration procedure were done in: https://github.com/phoenix-pilot/phoenix-pilot-core/pull/73/commits/c055cca111f38041a55c626053623878b88afc4b
- Changes to `magiton` calibration procedure were done in: https://github.com/phoenix-pilot/phoenix-pilot-core/pull/73/commits/e8c83e84978497fea5fb9ee90a540be43873b445

2022-09-09 12:55 UTC, HBuczynski approved these changes

2022-09-09 12:58 UTC, merged