P nieck/adding tests for matrix write submatrix
phoenix-pilot/phoenix-pilot-core pull request #76
Opened 2022-09-01 16:09 UTC by PNieck

JIRA: PP-71

## Description

This PR adds new functionali to `matrix_writeSubmatrix`. Now function returns $-1$ when it is impossible to write submatrix. Additionally test for this function where made.

## Motivation and Context

Safer functions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [] Already covered by automatic testing.
- [x] New test added: (add PR link here). In this PR
- [ ] Tested by hand on: (list targets here).

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-09-02 08:57 UTC, niewim19 requested changes
Maybe it is worth waiting for `matrix_prod()` tests to be merged to use tools declared there. Also:

 - fix spacing in preparation part of tests. Comments may stay if you want, there will be small inconsistency between these and other tests but rather editorial.
 - use known correct rowspan/colspan and half/double it to get different inconsistencies in tests where they are needed.
 - you can use `const matrix_t Exp` filled with correct data.

2022-09-02 08:57 UTC, niewim19 commented on algebra/matrix.c
> +	// const unsigned int Acols = A->cols, Bcols = B->cols; /* rewritten Acols and Bcols for better performance */
Thats not part of this PR, but please remove the unused line :) (probably left by me)

2022-09-02 08:57 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +			buffs_colsFwithBonRow0Col0 * buffs_rowsFwithBonRow0Col0));
- You have never described the preparation part in such detail :). After all it is quite self explanatory. You can also remove the spacing if you decide to remove comments
- You can do the same trick as in `matrix_prod()` PR: as expected data is constant, replace the Exp global with local, `const matrix_t Exp` and write proper data in-place.

This comment applies to almost all tests in this file

2022-09-02 08:57 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	TEST_ASSERT_EQUAL_FLOAT_ARRAY(Exp.data, M1.data, Exp.rows * Exp.cols);
Don't we have a function for that in `matrix_prod()` PR? Maybe it is worth waiting for that to merge and use it. I wonder if this can be refactored elsewhere in tests.

2022-09-02 08:57 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = 2, colToWrite = 6;
You can perform the same trick as in old `matrix_at()` tests: use known indices and double them if you need greater value and half them otherwise.

2022-09-02 08:57 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = 6, colToWrite = 2;
You can perform the same trick as in old `matrix_at()` tests: use known indices and double them if you need greater value and half them otherwise.

2022-09-02 08:57 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowsM2 = 10, colsM2 = 12;
You can perform the same trick as in old `matrix_at()` tests: use known indices and double them if you need greater value and half them otherwise.

2022-09-05 13:43 UTC, PNieck commented on algebra/matrix.c
> +	// const unsigned int Acols = A->cols, Bcols = B->cols; /* rewritten Acols and Bcols for better performance */
I have done it is this PR -> https://github.com/phoenix-pilot/phoenix-pilot-core/pull/70

2022-09-05 15:51 UTC, niewim19 requested changes
These tests need changes:

 - some names are very long, I have left some suggestions
 - don`t you think that all tests are possible from within one test group where you constantly use `F` and `B` matrices? Failure conditions can be established by halfing/subtracting `F` and `B` sizes 
 - some code repeats itself in test bodies and in SETUPS
 - You can mitigate magic numbers in test that _writes `B` into `F` in the middle_ with writing that matrix at the bottom right corner of `F`. Then just subtractions  on matrices sizes are needed

About refactoring `matrix.h`
 - what do you think about renaming `M1` and `M2` in function declaration to source, dest and parameters as destRow and destCol (with adequate comment change)?

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/buffs.h
> +static const float buffs_FwithBonRow0Col0[] = {
```suggestion
static const float buffs_BintoF_R0C0[] = { 
```
little convention break, but much more readable

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/buffs.h
> +static const float buffs_FwithBonRow5Col2[] = {
```suggestion
static const float buffs_BintoF_R5C2[] = { 
```

2022-09-05 15:51 UTC, niewim19 commented on algebra/matrix.c
>  	int cprow;
Declarations go first in function body

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST_GROUP(group_matrix_writeSubmatrix_usingMatFandB);
``` suggestion
TEST_GROUP(group_matrix_writeSubmatrix_partials);
```

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_writeSubmatrix_usingMatFandB, matrix_writeSubmatrix_writeOnMatrixBeginning)
```suggestion
TEST(group_matrix_writeSubmatrix_partials, matrix_writeSubmatrix_onStart)
```

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_writeSubmatrix_usingMatFandB, matrix_writeSubmatrix_writeOnMiddleOfMat)
```suggestion
TEST(group_matrix_writeSubmatrix_partials, matrix_writeSubmatrix_inMiddle)
```

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +		algebraTests_createAndFill(&M2, buffs_rowsB, buffs_colsB, buffs_B, buffs_colsB * buffs_rowsB));
Code repetition from SETUP?

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_writeSubmatrix_usingMatFandB, matrix_writeSubmatrix_notChangingMatrixToWrite)
Ok, this test is important and very unintuitive given only name which must be long to have all needed information. 
The name should be shorter,I propose `matrix_writeSubmatrix_sourceConst` and with a comment just above the test body that shortly describes what is checked.

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +		algebraTests_createAndFill(&M2, buffs_rowsB, buffs_colsB, buffs_B, buffs_colsB * buffs_rowsB));
code copied from setup. However this remark is nulled as this test should be moved to other group.

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_writeSubmatrix_std, matrix_writeSubmatrix_writingWholeMatrix)
```suggestion
TEST(group_matrix_writeSubmatrix_std, matrix_writeSubmatrix_fullWrite)
```

2022-09-05 15:51 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +TEST(group_matrix_writeSubmatrix_std, matrix_writeSubmatrix_matrixNotChangingAfterFail)
There are two very simmilar tests, both kind of checking data integrity. Maybe separate group is needed for such tests? Something like `group_matrix_writeSubmatrix_integrity` where you can import matrices `B` and `F` and do `matrix_writeSubmatrix_sourceRetain` and `matrix_writeSubmatrix_failureRetain`. Also here you use matrices B and F outside of their separate group, so you may also move them there

2022-09-06 15:15 UTC, niewim19 requested changes
Looks good.

 - we can drop long names both in buffers and in test (such as `colToWrite` etc)
 - use unsigned variables for col/row variables
 - some small editorial remarks

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = 5, colToWrite = 2;
Magic numbers. How about:
```suggestion
	unsigned row, col;
	
	row = matrix_rowsGet(M1) - matrix_rowsGet(M2);
	col = matrix_colsGet(M1) - matrix_colsGet(M2);
```
so that you write it at the end of the matrix (botton right corner)?

Also: we can stick to pure `col`, `row` notation

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M3, &M2));
```suggestion
	/* store copy of M2 in M3 */
	matrix_bufFree(&M3);
	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M3, &M2));
```

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M2, &M1));
```suggestion
	/* store copy of M1 in M2 */
	matrix_bufFree(&M2);
	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M2, &M1));
```

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = 0, colToWrite = M1.cols - M2.cols / 2;
Split for better readibility
```suggestion
	unsigned int row, col; 

	row = 0;
	col = M1.cols - M2.cols / 2;
```

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = M1.rows - M2.cols / 2, colToWrite = 0;
Split for better readibility as previous remark + use `row`, `col`

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	int rowToWrite = M1.rows, colToWrite = M1.cols;
Split for better readibility as previous remark + use `row`, `col`

2022-09-06 15:15 UTC, niewim19 commented on algebra/tests/matrix/various.c
> +	TEST_ASSERT_EQUAL_INT(BUF_ALLOC_OK, algebraTests_matrixCopy(&M3, &M1));
Previousely we freed the buffer we copied into

2022-09-07 13:04 UTC, niewim19 approved these changes
LGTM

2022-09-07 14:03 UTC, merged