algebra: adding tests for `matrix_sandwitch` function
phoenix-pilot/phoenix-pilot-core pull request #99
Opened 2022-09-08 15:17 UTC by PNieck

JIRA: PP-71

## Description

This PR contains tests for `matrix_sandwitch` function.

## Motivation and Context

More precise tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## How Has This Been Tested?

- [ ] Already covered by automatic testing.
- [ ] New test added: (add PR link here).
- [x] Tested by hand on: (list targets here). `armv7a9-zynq7000-qemu`

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing linter checks and tests passed.
- [ ] My changes generate no new compilation warnings for any of the targets.

## Special treatment

- [ ] This PR needs additional PRs to work (list the PRs, preferably in merge-order).
- [x] I will merge this PR by myself when appropriate.

2022-09-08 17:59 UTC, niewim19 requested changes
Generally good. Small changes requested.

2022-09-08 17:59 UTC, niewim19 commented on algebra/tests/matrix/buffs.h
> +    14,	-9,	-11
Strange formatting appeared

2022-09-08 17:59 UTC, niewim19 commented on algebra/tests/matrix/buffs.h
> +static const float buffs_AsandB[] = {
Please add commentary for these variables/buffers

2022-09-08 17:59 UTC, niewim19 commented on algebra/tests/matrix/sandwitch.c
> + * ############################################################################## */
Strange formatting appeared at the end

2022-09-08 17:59 UTC, niewim19 commented on algebra/tests/matrix/sandwitch.c
> +static int ROW, COL;
Let's just use local `row`/`col` declared in each test. And make them `unsigned`. That way it looks like macro and may be confusing

2022-09-08 17:59 UTC, niewim19 commented on algebra/tests/matrix/sandwitch.c
> +TEST(group_matrix_sandwitch_badMats, matrix_sandwitch_failureRetain)
How about `tmp` matrix?

2022-09-09 08:55 UTC, PNieck commented on algebra/tests/matrix/sandwitch.c
> +TEST(group_matrix_sandwitch_badMats, matrix_sandwitch_failureRetain)
I am checking if `tmp` is changing

2022-09-12 13:20 UTC, niewim19 requested changes

2022-09-12 13:20 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	int i;
Please, use `unsigned long`. Those arrays might have `(uint32_max * uint32_max)` size. It is highly unlikely that it will, but just to conform to sizes :)

2022-09-12 13:20 UTC, niewim19 commented on algebra/tests/matrix/sandwitch.c
> +TEST(group_matrix_sandwitch_badMats, matrix_sandwitch_failureRetain)
I know, but the comment does not state that :)

2022-09-12 13:25 UTC, niewim19 commented on algebra/tests/matrix/tools.c
> +	int i;
OK. After second thought this is unnecessary. Nobody is going to multiply 4294967295x4294967295 matrix using cpu in such a time that an error would occur

2022-09-12 13:31 UTC, niewim19 approved these changes
LGTM

2022-09-12 13:39 UTC, niewim19 approved these changes
LGTM

2022-09-12 13:49 UTC, merged